/// <summary>
/// C# Wrapper Class of Trispector.
/// </summary>
/// <remarks>
/// This is the C# API wrapper of C++ file trispector.cpp|h.
/// Copyright 2016-2021 SICK AG. All rights reserved.
/// Author: Vision Lab, SICK GCN
/// Version: 3.4.3.66
/// Date: 2020.09.21
/// </remarks>

#pragma once

#include "ImgTCSharpWrapper.h"
#include "CommonFunctions.h"
#include <Trispector.h>
#include <cliext\list>
#include <cliext\map>
#include <vcclr.h>
#include <msclr\lock.h>

#include <string>
#include <sstream>

#include <windows.h>

using namespace System;
using namespace System::Threading;
using namespace msclr;

//#define _CALLBACK_ON
#define _DISABLE_GrabberThread

namespace SICK3D
{
namespace TRI
{

private enum class RequireCode
{
	REQ_QUIT_RUN,
	REQ_STOP_CAMERA,
	REQ_Nothing
};

////////////////////////////////////////////////////////////////////////////////

static SPtr<SickCam::TrispectorShared> gp_TriS;

typedef array<String^>^ deviceList;

/// <summary>
/// 【警告：旧接口。请优先使用 SwigRanger3 】
/// GenICam 3D Trispector 相机类
/// </summary>
public ref class GenICam3D_Tri
{
public:
	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 构造函数。请确保 cti 文件和 exe 文件处于同一文件夹内。cti 文件是二进制文件，其作用类似于dll，是基础程序集的一部分，由 IVP 提供。
	/// CTI file should be in the same folder with exe. The cti is a binary file generated by IVP, which is a API library.
	/// </summary>
	/// <param name="logPath">日志文件路径，设为""则使用默认路径。The log file path. if it equals to "", using the default.</param>
	/// <param name="ctiPath">cti 文件路径，设为""则使用默认路径。The cti file path. if it equals to "", using the default.</param>
	/// <param name="enShow">true 则输出日志内容到命令行。 true means to print log to CMD.</param>
	/// <param name="enWrite">true 则输出日志内容到文件。 true means to print log to file.</param>
	/// <remarks>
	/// 构造函数的基本动作包括：
	/// - 1. 设定该程序的最高优先级，保证在被 CPU 执行期间不受干扰。
	/// - 2. 加载日志。默认文件路径为： exe 文件路径 + "_时间_log.txt"。
	/// - 3. 加载 cti 文件。默认查找范围为 exe 文件所在文件夹。
	/// scanDevice() 将会被构造函数调用，用于扫描所有已连接到电脑的设备。
	/// 
	/// Construction processes include:
	/// - 1. Set thread priority as highest.
	/// - 2. Load log file. The default path is exe-path + "_time_log.txt".
	/// - 3. Load cti file, The default searching folder is exe-folder.
	/// scanDevice() will be called by ctor to scan all device connected to PC.
	/// </remarks>
	GenICam3D_Tri(const String^ logPath,
		const String^ ctiPath,
		const bool enShow,
		const bool enWrite);

	~GenICam3D_Tri();

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取连接到电脑的设备名列表，以及设备对象指针。 To get the ptr map of devices.
	/// </summary>
	/// <returns>设备名列表 std::map&lt;device_name_string, device_ptr&gt;</returns>
	deviceList	getConDevList();

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取连接到电脑的设备IP列表，以及设备对象指针。 To get the ptr map of devices, marked with SN.
	/// </summary>
	/// <returns>设备SN列表 std::map&lt;device_MAC_string, device_ptr&gt;</returns>
	deviceList	getConDevListSN();

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取连接到电脑的设备列表。 To scan all device connected to PC.
	/// </summary>
	/// <returns>
	/// - ERROR_OPEN_TL_HANDLE 打开 GenTL 失败。Can not open GenTL of GenICam.
	/// - ERROR_SCAN_EMPTY_DEVICE 没找到设备。No one is found.
	/// - All_OK 找到设备。Found.
	/// </returns>
	CAM_STATUS	scanDevice() { return static_cast<CAM_STATUS>(gp_TriS->scanDevice()); }

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 加载 cti 文件。 To load cti file of given path.
	/// </summary>
	/// <param name="ctiPath">cti 文件路径。The cti file path.</param>
	/// <returns>
	/// - ERROR_OPEN_CONSUMER 打开 consumer 失败。Can not open consumer model of GenICam.
	/// - All_OK
	/// </returns>
	/// <remarks>
	/// cti 文件由 SICK 生成。此函数将在 ctor 中调用。如果 ( isCtiFound() == false &amp;&amp; isAvaliable() == false )，
	/// 请手动调用它并传递有效的 cti 文件路径。
	/// 
	/// The cti file is generated by SICK. This function will be called in ctor.
	/// If ( isCtiFound() == false &amp;&amp; isAvaliable() == false ), please call it manually and passing valid cti file path.
	/// </remarks>
	CAM_STATUS	loadCtiFile(const String^ ctiPath)
	{
		return static_cast<CAM_STATUS>(gp_TriS->loadCtiFile(StringRef2string(ctiPath)));
	}

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取初始化结果，检测 cti 文件 和 连接设备是否都存在。 To check initialization result. Check both CTI file and avaliable device
	/// </summary>
	/// <returns>
	/// - true OK. cti文件存在，并且找到连接设备。 Both CTI file and avaliable device found!
	/// - false 未连接任何设备、设备未就绪或加载 cti 文件失败！ No device is connected, device is not ready or loading cti file failed!
	/// </returns>
	/// <remarks>结果为：isCtiFound() &amp;&amp; isDevFound();</remarks>
	bool		isAvaliable() { return gp_TriS->isAvaliable(); };

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取 cti 文件导入结果。 To check load cti result.
	/// </summary>
	/// <returns>
	/// - true OK.
	/// - false cti 文件路径无效，或者未指定。
	/// </returns>
	bool		isCtiFound() { return gp_TriS->isCtiFound(); };

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取设备扫描结果。 To check device scaning result.
	/// </summary>
	/// <returns>
	/// - true OK.
	/// - false 未连接任何设备、设备未就绪！ No device is connected, device is not ready!
	/// </returns>
	bool		isDevFound() { return gp_TriS->isDevFound(); };

	bool		isLogOutput() { return gp_TriS->isLogOutput(); };
	bool		isLogToFile() { return gp_TriS->isLogToFile(); };

	void 		_release();
	static String^ getPathToTrispectorProducer();

private:

};


////////////////////////////////////////////////////////////////////////////////

#ifndef _DISABLE_GrabberThread
ref class CLR_Mutex {};
private ref class GrabberThread
{
public:
	GrabberThread(SickCam::Trispector * pTri);
	~GrabberThread();

	void	run();
	CSImgT^ getData();
	void	setSleepTime(const unsigned int sleepTime) { lock l(locker_sleepTime);	m_sleepTime = sleepTime; }
	int		getSleepTime() { lock l(locker_sleepTime); return m_sleepTime; };

	bool	sendRequest(const RequireCode req);

	bool	isFinishGrab() { return m_IsFinishGrab; }
	bool	isRun() { return m_IsRun; }
	bool	isGrabbed() { lock l(locker_data); return !m_ImageData.empty(); }

protected:
	// return true to break run().
	bool	_doRequest();
	bool	_clear_and_break();

private:
	SickCam::Trispector *  mp_tri;

	// modified by different threads
	cliext::list<CSImgT^> m_ImageData;
	RequireCode m_req;
	unsigned int m_sleepTime;

	// status
	bool m_IsGrabbed;
	bool m_IsRun;
	bool m_IsFinishGrab;

	// locker
	Object^ locker_data;
	Object^ locker_req;
	Object^ locker_sleepTime;

};

////////////////////////////////////////////////////////////////////////////////
#ifdef _CALLBACK_ON
private ref class GrabberCallback
{
public:
	GrabberCallback(R3 * pr3) {};

	void	_callback_run();
	void	_callback_run_on_grabbed(Object^ _img);

	Object^				m_callBack_inputs;
	bool				m_callback_is_on;
	bool				m_callback_is_finish_copy;
	Object^				m_callback_is_finish_copy_locker;
	bool				m_callback_require_stop;
	Object^				m_callback_require_stop_locker;


	R3 *  mp_tri;

};
#endif
#endif
////////////////////////////////////////////////////////////////////////////////

/// <summary>
/// 【警告：旧接口。请优先使用 SwigRanger3 】
/// </summary>
public ref class Trispector
{
public:

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// Trispector 相机专用初始化函数。 For Trispector.
	/// </summary>
	/// <param name="sn">相机的 SN 号。Trispector 必须使用 SN 来指定相机。SN is the only choice.</param>
	Trispector(const String ^ sn);
	~Trispector();

public:

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取初始化结果。 To get initialization result.
	/// </summary>
	/// <returns>
	/// - CAM_STATUS::ERROR_NULL_PTR_DEV 初始化失败。 Initialize failed.
	/// - CAM_STATUS::All_OK
	/// </returns>
	CAM_STATUS	isReady();

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 连接相机。 Connect a camera.
	/// </summary>
	/// <param name="enable_CPP_Grab_thread">必须设置为 true。 Must set it true;</param>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_STARTED 相机处于 start 状态。 Camera is started.
	/// - CAM_STATUS::ERROR_SCAN_PARAMETERS 扫描相机参数时发生错误。 Error happened when scaning parameters in device.
	/// </returns>
	/// <remarks>
	/// 连接相机的动作包括：打开设备句柄，打开数据流句柄，加载参数文件，扫描相机参数。
	/// 当相机连接时，采集图像过程并没有开始。
	/// 
	/// It will open device handle, open datastream, loading parameters file, scan parameters in device.
	/// When camera is connected, image acquition is not started.
	/// </remarks>
	CAM_STATUS	connectCamera(const bool enable_CPP_Grab_thread);

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 开始采集。 Start acquisition.
	/// </summary>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED 相机处于 disconnect 状态。 Camera is disconnected.
	/// - CAM_STATUS::ERROR_START_ACQUISITION 相机开始采集失败。 Failed to start acquisition.
	/// - CAM_STATUS::ERROR_CALIBRATION_PATH 使用标定文件初始化标定变量错误。 Error happened when initialzing calibration variables.
	/// </returns>
	/// <remarks>
	/// 开始采集的动作包括：加载标定文件，申请相机缓存，锁定相机参数，开始采集图像。
	/// 
	/// It will load calibration file, initialize device buffer, lock device parameter, start acquisition.
	/// </remarks>
	CAM_STATUS	startCamera();

#ifdef _CALLBACK_ON
	//typedef void(__stdcall CallbackEvent^)			(CSImgT^ img, Object^ any);
	delegate void CallbackEvent(CSImgT^ img, Object^ any); // todo -------

	/// <summary>
	/// 开始采集，并启动 callback。 Start acquisition and passing callback function
	/// </summary>
	/// <param name="pCallback">Callback funtion pointer;</param>
	/// <param name="any">在 callback 中要使用的参数。 The parameters will be passed into callback funtion;</param>
	/// <returns>
	/// - All_OK
	/// - ERROR_CAM_IS_DISCONNECTED 相机处于 disconnect 状态。 Camera is disconnected.
	/// - ERROR_START_ACQUISITION 相机开始采集失败。 Failed to start acquisition.
	/// - ERROR_CALIBRATION_PATH 使用标定文件初始化标定变量错误。 Error happened when initialzing calibration variables.
	/// </returns>
	/// <remarks>
	/// 开始采集的动作包括：加载标定文件，申请相机缓存，锁定相机参数，开始采集图像。
	/// Callback 函数中的第一个参数是返回的图像。其内存由 API 管理，在 callback 函数调用结束后，API 将释放 ImgT 中的内存。
	/// 所以，使用者在拿到数据之后，应该第一时间做"深拷贝"。
	/// ImgT 中的操作符 = ，已经重载为深拷贝。
	/// 
	/// It will load calibration file, initialize device buffer, lock device parameter, start acquisition.
	/// </remarks>
	CAM_STATUS	startCamera(CallbackEvent^ pCallback, Object^ any);
#endif

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 停止采集。 Stop acquisition.
	/// </summary>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED 相机处于 disconnect 状态。 Camera is disconnected.
	/// - CAM_STATUS::ERROR_STOP_ACQUISITION 相机停止采集失败。 Failed to stop acquisition.
	/// </returns>
	/// <remarks>
	/// 停止采集的动作包括：停止采集图像，解锁相机参数，清除相机缓存。本质上 connected 和 stopped 是一样的状态。
	/// 
	/// It will stop acquisition, unlock device parameter, free device buffer. Actually, connected equals to stopped.
	/// </remarks>
	CAM_STATUS	stopCamera();

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 断开相机连接。 Disconnect a camera.
	/// </summary>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_STARTED 相机处于 start 状态。 Camera is started.
	/// - CAM_STATUS::UNKNOW 未知错误。 Unknown problem.
	/// </returns>
	/// <remarks>
	/// 断开相机连接的动作包括：关闭数据流句柄，关闭设备句柄。
	/// 
	/// It will close datastream, close device handle.
	/// </remarks>
	CAM_STATUS	disconnectCamera();

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 获取图像。 Get output images.
	/// </summary>
	/// <param name="imgTable">Images data;</param>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_STARTED 相机处于 start 状态。 Camera is started.
	/// - CAM_STATUS::ERROR_IMAGE_NOT_READY 线程未采集到图像，CLR 部分独有。
	/// </returns>
	/// <remarks>相机必须处于 start 状态时才可以采集图像。请注意，非线程安全。 Camera must be started! And it is not thread-safe.</remarks>
	CAM_STATUS	getImageData(CSImgT^ imgTable);

	/// <summary>
	/// 设置内置轮询线程的循环等待时间，单位毫米。建议一般在 start 之前设置，理论上可以在任何时候设置。
	/// </summary>
	/// <param name="sleepTime">默认 50 ms. The default is 50 ms.</param>
	/// <returns>操作状态</returns>
	CAM_STATUS	setGrabSleepTime(const unsigned int sleepTime);

	/// <summary>
	/// 读取内置轮询线程的循环等待时间，单位毫米。
	/// </summary>
	/// <returns>等待时间，单位毫秒</returns>
	unsigned int getGrabSleepTime();


	////////////////////////////////////////////////////////////////////////////////

	/// <summary>
	/// 【警告：旧接口。请优先使用 SwigRanger3 】
	/// 设置 Y 方向分辨率。 Set scale in Y axis.
	/// </summary>
	/// <param name="value">value = (y_range_in_mm) / (profiles_number).</param>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_STARTED 相机处于 start 状态。 Camera is started.
	/// - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED 相机处于 disconnect 状态。 Camera is disconnected.
	/// </returns>
	/// <remarks>
	/// 点云 y 坐标 = Y_offset + Y_scale * Y_pixelValueInRange。
	/// Y value of a pointcloud = Y_offset + Y_scale * Y_pixelValueInRange.
	/// </remarks>
	CAM_STATUS	setScaleY(const double value) { return static_cast<CAM_STATUS>(mp_tri->setScaleY(value)); };

	/// <summary>
	/// 设置相机取图的最大等待时间。 Set timeout.
	/// </summary>
	/// <param name="value">相机取图的最大等待时间，单位毫秒。 Maximum waiting time when grabbing image, unit is millimeter.</param>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_STARTED 相机处于 start 状态。 Camera is started.
	/// - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED 相机处于 disconnect 状态。 Camera is disconnected.
	/// </returns>
	CAM_STATUS	setTimeOut(const int value) { return static_cast<CAM_STATUS>(mp_tri->setTimeOut(value)); };

	/// <summary>
	/// 设置图像缓存的张数。 Set the number of image buffers.
	/// </summary>
	/// <param name="value">图像缓存的张数。 The number of image buffers.</param>
	/// <returns>
	/// - CAM_STATUS::All_OK
	/// - CAM_STATUS::ERROR_CAM_IS_STARTED 相机处于 start 状态。 Camera is started.
	/// - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED 相机处于 disconnect 状态。 Camera is disconnected.
	/// </returns>
	/// <remarks>
	/// 默认是 20 ，最小可以设置为 1。设置越大，内存占用越多。设置太小，有丢帧风险。
	/// The default is 20, avaliable minimum value can be 1. The bigger value, the more memory will be allocated. The smaller value, the higher risk of miss a frame.
	/// </remarks>
	CAM_STATUS	setBufferCount(const int value) { return static_cast<CAM_STATUS>(mp_tri->setBufferCount(value)); };


	////////////////////////////////////////////////////////////////////////////////

	/// <summary>
	/// 读取 Y 方向分辨率。 Get scale in Y axis.
	/// </summary>
	/// <returns>Y 方向分辨率</returns>
	/// <remarks>
	/// 点云 y 坐标 = Y_offset + Y_scale * Y_pixelValueInRange。
	/// Y value of a pointcloud = Y_offset + Y_scale * Y_pixelValueInRange。
	/// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
	/// Camera shoudl be connected or stopped.
	/// </remarks>
	double	getScaleY() { return mp_tri->getScaleY(); }

	/// <summary>
	/// 读取相机取图的最大等待时间，单位毫秒。 Get maximum waiting time when grabbing image, unit is millimeter.
	/// </summary>
	/// <returns>等待时间，单位毫秒</returns>
	/// <remarks>建议在相机处于 connected 或者 Stopped 状态时，执行该操作。 Camera shoudl be connected or stopped.</remarks>
	int		getTimeOut() { return static_cast<int>(mp_tri->getTimeOut()); }

	/// <summary>
	/// 读取图像缓存的张数。 Get the number of image buffers.
	/// </summary>
	/// <returns>图像缓存的张数</returns>
	/// <remarks>
	/// 默认是 20 ，最小可以设置为 1。设置越大，内存占用越多。设置太小，有丢帧风险。
	/// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
	/// The default is 20, avaliable minimum value can be 1. The bigger value, the more memory will be allocated. The smaller value, the higher risk of miss a frame.
	/// Camera shoudl be connected or stopped.
	/// </remarks>
	int		getBufferCount() { return static_cast<int>(mp_tri->getBufferCount()); }

	/// <summary>
	/// 获取设备名。 Device name format : "SICKGigEVisionTL_DEV_" + mac + "_Ranger3"
	/// </summary>
	/// <returns>设备名，错误时返回空字符串。 return "" when error happened.</returns>
	/// <remarks>支持任何相机状态下读取。 It can be queried in any camera status.</remarks>
	String^	getDeviceName();


	/// <summary>
	/// 读取相机状态。 Get camera status.
	/// </summary>
	/// <returns>
	/// - CAM_STATUS::CAM_IS_CONNECTED 相机已连接 Connected
	/// - CAM_STATUS::CAM_IS_STARTED 相机开始采集 Start acquisition
	/// - CAM_STATUS::CAM_IS_STOPPED 相机停止采集 Stop acquisition
	/// - CAM_STATUS::CAM_IS_DISCONNECTED 相机未连接 Disconnected
	/// - CAM_STATUS::ERROR_NULL_PTR_DEV 类 Trispector 的对象未初始化完成。 Class Trispector initialization undone.
	/// </returns>
	CAM_STATUS	getStatus() { return static_cast<CAM_STATUS>(mp_tri->getStatus()); };

	/// <summary>
	/// 读取图像序号，也是当前取到的图像总数，stop 后清理。 Get image ID. The value is also the number of grabbed image. Reset to 0 when stopped.
	/// </summary>
	/// <returns>图像序号</returns>
	/// <remarks>0初始。相机必须处于 connected 或者 stopped 状态。 Start from 0. The camera must be connected or stopped when calling this.</remarks>
	int			getImgID() { return static_cast<int>(mp_tri->getImgID()); }


	////////////////////////////////////////////////////////////////////////////////

	bool		isGrabbed(const String^ do_not_use_any_more) { return false; /* mp_gt->isGrabbed(); */ }

	////////////////////////////////////////////////////////////////////////////////
protected:


private:
	SickCam::Trispector *  mp_tri;

	////////////////////////////////////////////////////////////////////////////////
#ifndef _DISABLE_GrabberThread

	bool				m_enable_CPP_Grab_thread;
	Thread^				m_Thread;
	GrabberThread^ 		mp_gt;

	Object^				locker_GetData;
	Object^				locker_Start;

	////////////////////////////////////////////////////////////////////////////////
#ifdef _CALLBACK_ON
	CallbackEvent^		m_callBack_function;

	GrabberCallback^	mp_cb;
#endif 

#endif 

};

}

}
