//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>标定的高度数据信息  Calibration data information.</summary>

public class CalibInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CalibInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CalibInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CalibInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CalibInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_CalibInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CalibInfo() : this(SwigRanger3PINVOKE.new_CalibInfo(), true) {
  }

  ///  视野在 X 方向的最小值，毫米。					Unit millimeter, minimum x in FOV
  public double offsetX {
    set {
      SwigRanger3PINVOKE.CalibInfo_offsetX_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_offsetX_get(swigCPtr);
      return ret;
    } 
  }

  ///  视野在 Y 方向的最小值，毫米。					Unit millimeter, minimum y in FOV
  public double offsetY {
    set {
      SwigRanger3PINVOKE.CalibInfo_offsetY_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_offsetY_get(swigCPtr);
      return ret;
    } 
  }

  /// 【此参数仅在启用相机内部（in-device）标定时有效，（in-PC）标定时此参数没有意义，可以给 0.0】视野在 Z 方向的最小值，毫米。
  /// 																						Unit millimeter, minimum z in FOV
  public double offsetZ {
    set {
      SwigRanger3PINVOKE.CalibInfo_offsetZ_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_offsetZ_get(swigCPtr);
      return ret;
    } 
  }

  ///  视野在 X 方向的分辨率，毫米/像素。				Unit millimeter/pixel, x resolution
  public double scaleX {
    set {
      SwigRanger3PINVOKE.CalibInfo_scaleX_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_scaleX_get(swigCPtr);
      return ret;
    } 
  }

  ///  视野在 Y 方向的分辨率，毫米/像素。				Unit millimeter/pixel, y resolution
  public double scaleY {
    set {
      SwigRanger3PINVOKE.CalibInfo_scaleY_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_scaleY_get(swigCPtr);
      return ret;
    } 
  }

  /// 【此参数仅在启用相机内部（in-device）标定时有效，（in-PC）标定时此参数没有意义，可以给 1.0】视野在 Z 方向的分辨率，毫米/像素。
  /// 																						Unit millimeter/pixel, z resolution
  public double scaleZ {
    set {
      SwigRanger3PINVOKE.CalibInfo_scaleZ_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_scaleZ_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 视野在 X 方向的最小值，毫米。	Unit millimeter, minimum x in FOV
  public double lower_bound_x {
    set {
      SwigRanger3PINVOKE.CalibInfo_lower_bound_x_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_lower_bound_x_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 视野在 X 方向的最大值，毫米。	Unit millimeter, maximum x in FOV
  public double upper_bound_x {
    set {
      SwigRanger3PINVOKE.CalibInfo_upper_bound_x_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_upper_bound_x_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 视野在 R 方向的最小值，毫米。激光竖直架设，R 就是 Z 轴。	Unit millimeter, minimum r in FOV, when set lazer vertically, same as z
  public double lower_bound_r {
    set {
      SwigRanger3PINVOKE.CalibInfo_lower_bound_r_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_lower_bound_r_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 视野在 R 方向的最大值，毫米。激光竖直架设，R 就是 Z 轴。	Unit millimeter, maximum r in FOV, when set lazer vertically, same as z
  public double upper_bound_r {
    set {
      SwigRanger3PINVOKE.CalibInfo_upper_bound_r_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.CalibInfo_upper_bound_r_get(swigCPtr);
      return ret;
    } 
  }

  public genistreamtraits_ genistreamtraits {
    set {
      SwigRanger3PINVOKE.CalibInfo_genistreamtraits_set(swigCPtr, genistreamtraits_.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SwigRanger3PINVOKE.CalibInfo_genistreamtraits_get(swigCPtr);
      genistreamtraits_ ret = (cPtr == global::System.IntPtr.Zero) ? null : new genistreamtraits_(cPtr, false);
      return ret;
    } 
  }

}

}
