//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {

public class CameraShared : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CameraShared(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CameraShared obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CameraShared obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CameraShared() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_CameraShared(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CameraShared(string logPath, string ctiPath, bool enShow, bool enWrite) : this(SwigRanger3PINVOKE.new_CameraShared__SWIG_0(logPath, ctiPath, enShow, enWrite), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public CameraShared(string logPath, string ctiPath, bool enShow) : this(SwigRanger3PINVOKE.new_CameraShared__SWIG_1(logPath, ctiPath, enShow), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public CameraShared(string logPath, string ctiPath) : this(SwigRanger3PINVOKE.new_CameraShared__SWIG_2(logPath, ctiPath), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public CameraShared(string logPath) : this(SwigRanger3PINVOKE.new_CameraShared__SWIG_3(logPath), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_deviceList getConDevList(bool available_device_only) {
    SWIGTYPE_p_deviceList ret = new SWIGTYPE_p_deviceList(SwigRanger3PINVOKE.CameraShared_getConDevList__SWIG_0(swigCPtr, available_device_only), true);
    return ret;
  }

  public SWIGTYPE_p_deviceList getConDevList() {
    SWIGTYPE_p_deviceList ret = new SWIGTYPE_p_deviceList(SwigRanger3PINVOKE.CameraShared_getConDevList__SWIG_1(swigCPtr), true);
    return ret;
  }

  public CAM_STATUS scanDevice(out int numberDeviceNewFound) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.CameraShared_scanDevice__SWIG_0(swigCPtr, out numberDeviceNewFound);
    
    return ret;
}

  public CAM_STATUS scanDevice() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.CameraShared_scanDevice__SWIG_1(swigCPtr);
    
    return ret;
}

  public SWIGTYPE_p_CAM_STATUS loadCtiFile(string ctiPath) {
    SWIGTYPE_p_CAM_STATUS ret = new SWIGTYPE_p_CAM_STATUS(SwigRanger3PINVOKE.CameraShared_loadCtiFile(swigCPtr, ctiPath), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isAvaliable() {
    bool ret = SwigRanger3PINVOKE.CameraShared_isAvaliable(swigCPtr);
    return ret;
  }

  public bool isCtiFound() {
    bool ret = SwigRanger3PINVOKE.CameraShared_isCtiFound(swigCPtr);
    return ret;
  }

  public bool isDevFound() {
    bool ret = SwigRanger3PINVOKE.CameraShared_isDevFound(swigCPtr);
    return ret;
  }

  public bool isLogOutput() {
    bool ret = SwigRanger3PINVOKE.CameraShared_isLogOutput(swigCPtr);
    return ret;
  }

  public bool isLogToFile() {
    bool ret = SwigRanger3PINVOKE.CameraShared_isLogToFile(swigCPtr);
    return ret;
  }

  public string getLastErrorMessage() {
    string ret = SwigRanger3PINVOKE.CameraShared_getLastErrorMessage(swigCPtr);
    return ret;
  }

  public string getVersion() {
    string ret = SwigRanger3PINVOKE.CameraShared_getVersion(swigCPtr);
    return ret;
  }

  public string getVersionTime() {
    string ret = SwigRanger3PINVOKE.CameraShared_getVersionTime(swigCPtr);
    return ret;
  }

  public static string getPathToRanger3Producer() {
    string ret = SwigRanger3PINVOKE.CameraShared_getPathToRanger3Producer();
    return ret;
  }

  public static string getPathToTrispectorProducer() {
    string ret = SwigRanger3PINVOKE.CameraShared_getPathToTrispectorProducer();
    return ret;
  }

  public string[] getConDevListMAC() {
    StringVector temp = new StringVector(SwigRanger3PINVOKE.CameraShared_getConDevListMAC(swigCPtr), false);
    string[] ret = temp.ToArray();
    
    return ret;
}

  public string[] getConDevListIP() {
    StringVector temp = new StringVector(SwigRanger3PINVOKE.CameraShared_getConDevListIP(swigCPtr), false);
    string[] ret = temp.ToArray();
    
    return ret;
}

  public string[] getConDevListSN() {
    StringVector temp = new StringVector(SwigRanger3PINVOKE.CameraShared_getConDevListSN(swigCPtr), false);
    string[] ret = temp.ToArray();
    
    return ret;
}

}

}
