//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {

public class DataNamesVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<DataNames>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DataNamesVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DataNamesVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DataNamesVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DataNamesVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_DataNamesVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DataNamesVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (DataNames element in c) {
      this.Add(element);
    }
  }

  public DataNamesVector(global::System.Collections.Generic.IEnumerable<DataNames> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (DataNames element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public DataNames this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(DataNames[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(DataNames[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, DataNames[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public DataNames[] ToArray() {
    DataNames[] array = new DataNames[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<DataNames> global::System.Collections.Generic.IEnumerable<DataNames>.GetEnumerator() {
    return new DataNamesVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new DataNamesVectorEnumerator(this);
  }

  public DataNamesVectorEnumerator GetEnumerator() {
    return new DataNamesVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class DataNamesVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<DataNames>
  {
    private DataNamesVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public DataNamesVectorEnumerator(DataNamesVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public DataNames Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (DataNames)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public DataNamesVector() : this(SwigRanger3PINVOKE.new_DataNamesVector__SWIG_0(), true) {
  }

  public DataNamesVector(DataNamesVector other) : this(SwigRanger3PINVOKE.new_DataNamesVector__SWIG_1(DataNamesVector.getCPtr(other)), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    SwigRanger3PINVOKE.DataNamesVector_Clear(swigCPtr);
  }

  public void Add(DataNames x) {
    SwigRanger3PINVOKE.DataNamesVector_Add(swigCPtr, (int)x);
  }

  private uint size() {
    uint ret = SwigRanger3PINVOKE.DataNamesVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = SwigRanger3PINVOKE.DataNamesVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = SwigRanger3PINVOKE.DataNamesVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    SwigRanger3PINVOKE.DataNamesVector_reserve(swigCPtr, n);
  }

  public DataNamesVector(int capacity) : this(SwigRanger3PINVOKE.new_DataNamesVector__SWIG_2(capacity), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  private DataNames getitemcopy(int index) {
    DataNames ret = (DataNames)SwigRanger3PINVOKE.DataNamesVector_getitemcopy(swigCPtr, index);
    
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
}

  private DataNames getitem(int index) {
    DataNames ret = (DataNames)SwigRanger3PINVOKE.DataNamesVector_getitem(swigCPtr, index);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, DataNames val) {
    SwigRanger3PINVOKE.DataNamesVector_setitem(swigCPtr, index, (int)val);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(DataNamesVector values) {
    SwigRanger3PINVOKE.DataNamesVector_AddRange(swigCPtr, DataNamesVector.getCPtr(values));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public DataNamesVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = SwigRanger3PINVOKE.DataNamesVector_GetRange(swigCPtr, index, count);
    DataNamesVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataNamesVector(cPtr, true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, DataNames x) {
    SwigRanger3PINVOKE.DataNamesVector_Insert(swigCPtr, index, (int)x);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, DataNamesVector values) {
    SwigRanger3PINVOKE.DataNamesVector_InsertRange(swigCPtr, index, DataNamesVector.getCPtr(values));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    SwigRanger3PINVOKE.DataNamesVector_RemoveAt(swigCPtr, index);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    SwigRanger3PINVOKE.DataNamesVector_RemoveRange(swigCPtr, index, count);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public static DataNamesVector Repeat(DataNames value, int count) {
    global::System.IntPtr cPtr = SwigRanger3PINVOKE.DataNamesVector_Repeat((int)value, count);
    DataNamesVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataNamesVector(cPtr, true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    SwigRanger3PINVOKE.DataNamesVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    SwigRanger3PINVOKE.DataNamesVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, DataNamesVector values) {
    SwigRanger3PINVOKE.DataNamesVector_SetRange(swigCPtr, index, DataNamesVector.getCPtr(values));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

}

}
