//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {

/// <summary>输出图像的类型。 Names of output Datas.</summary>
public enum DataNames {
  ///  INVALID	*	| INVALID		| 无效值					| INVALID														
  INV = 0,
  ///  uint8_t	*	| [---]			| 激光线图像				| SENSOR														
  SEN,
  ///  uint16_t	*	| [Raw]			| 高度图像				| ComponentSelector_Range_______RegionSelector_Scan3dExtraction1
  RAN,
  ///  uint8_t	*	| [Raw]			| 激光强度图像			| ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1
  REF,
  ///  uint8_t	*	| [Raw]			| 激光散射图像			| 8_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction1
  SCA_8,
  ///  uint16_t	*	| [Raw]			| 激光散射图像			| 16_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction1
  SCA_16,
  ///  uint32_t	*	| [---]			| 编码器信息				| Encoder_information
  MAR,
  ///  float		*	| [Calibrated]	| 标定后的高度图像			| ComponentSelector_Range_______RegionSelector_Scan3dExtraction1
  RAN_CAL,
  ///  uint16_t	*	| [Calibrated]	| 标定后的高度图像			| ComponentSelector_Range_______RegionSelector_Scan3dExtraction1
  RAN_CAL_16,
  ///  uint8_t	*	| [Calibrated]	| 标定后的激光强度图像		| ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1
  REF_CAL,
  ///  弃用		*	| [弃用]			| 弃用					| 弃用															
  REF_CAL_F,
  ///  uint8_t	*	| [Calibrated]	| 标定后的激光散射图像		| 8_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction1
  SCA_8_CAL,
  ///  uint16_t	*	| [Calibrated]	| 标定后的激光散射图像		| 16_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction1
  SCA_16_CAL,
  ///  uint16_t	*	| [Raw]			| 高度图像 2				| ComponentSelector_Range_______RegionSelector_Scan3dExtraction2
  RAN2,
  ///  uint8_t	*	| [Raw]			| 激光强度图像 2			| ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction2
  REF2,
  ///  uint8_t	*	| [Raw]			| 激光散射图像 2			| 8_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction2
  SCA2_8,
  ///  uint16_t	*	| [Raw]			| 激光散射图像 2 			| 16_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction2
  SCA2_16,
  ///  float		*	| [Calibrated]	| 标定后的高度图像 2		| ComponentSelector_Range_______RegionSelector_Scan3dExtraction2
  RAN2_CAL,
  ///  uint8_t	*	| [Calibrated]	| 标定后的激光强度图像 2	| ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction2
  REF2_CAL,
  ///  uint8_t    *	| [Calibrated]	| 标定后的激光散射图像 2	| 8_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction2
  SCA2_8_CAL,
  ///  uint16_t   *	| [Calibrated]	| 标定后的激光散射图像 2	| 16_Byte_ComponentSelector_Scatter_____RegionSelector_Scan3dExtraction2
  SCA2_16_CAL,
  ///  float		*	| [Calibrated]  | 仅标定，无校正，X 数据。 | Float32_RangeA
  RAN_X,
  ///  uint16_t	*	| [Calibrated]  | 仅标定，无校正，X 数据。 | 16_Byte_RangeA
  RAN_X_16,
  ///  uint16_t	*	| [Raw]			| 高精度灰度图像			| White
  WHITE,
  ///  uint16_t	*	| [Raw]			| 彩色图像 Red 通道		| R
  R,
  ///  uint16_t	*	| [Raw]			| 彩色图像 Red 通道		| G
  G,
  ///  uint16_t	*	| [Raw]			| 彩色图像 Red 通道		| B
  B
}

}
