//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>标定的高度数据信息  Calibration data information.</summary>

public class genistreamtraits_ : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal genistreamtraits_(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(genistreamtraits_ obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(genistreamtraits_ obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~genistreamtraits_() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_genistreamtraits_(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string region_id {
    set {
      SwigRanger3PINVOKE.genistreamtraits__region_id_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__region_id_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string extraction_method {
    set {
      SwigRanger3PINVOKE.genistreamtraits__extraction_method_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__extraction_method_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string output_mode {
    set {
      SwigRanger3PINVOKE.genistreamtraits__output_mode_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__output_mode_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int width {
    set {
      SwigRanger3PINVOKE.genistreamtraits__width_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      SwigRanger3PINVOKE.genistreamtraits__height_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__height_get(swigCPtr);
      return ret;
    } 
  }

  public int offset_X {
    set {
      SwigRanger3PINVOKE.genistreamtraits__offset_X_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__offset_X_get(swigCPtr);
      return ret;
    } 
  }

  public int offset_Y {
    set {
      SwigRanger3PINVOKE.genistreamtraits__offset_Y_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__offset_Y_get(swigCPtr);
      return ret;
    } 
  }

  public double a_axis_range_scale {
    set {
      SwigRanger3PINVOKE.genistreamtraits__a_axis_range_scale_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.genistreamtraits__a_axis_range_scale_get(swigCPtr);
      return ret;
    } 
  }

  public double a_axis_range_offset {
    set {
      SwigRanger3PINVOKE.genistreamtraits__a_axis_range_offset_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.genistreamtraits__a_axis_range_offset_get(swigCPtr);
      return ret;
    } 
  }

  public int a_axis_range_min {
    set {
      SwigRanger3PINVOKE.genistreamtraits__a_axis_range_min_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__a_axis_range_min_get(swigCPtr);
      return ret;
    } 
  }

  public int a_axis_range_max {
    set {
      SwigRanger3PINVOKE.genistreamtraits__a_axis_range_max_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__a_axis_range_max_get(swigCPtr);
      return ret;
    } 
  }

  public string a_axis_range_missing {
    set {
      SwigRanger3PINVOKE.genistreamtraits__a_axis_range_missing_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__a_axis_range_missing_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int a_axis_range_missing_value {
    set {
      SwigRanger3PINVOKE.genistreamtraits__a_axis_range_missing_value_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__a_axis_range_missing_value_get(swigCPtr);
      return ret;
    } 
  }

  public double b_axis_range_scale {
    set {
      SwigRanger3PINVOKE.genistreamtraits__b_axis_range_scale_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.genistreamtraits__b_axis_range_scale_get(swigCPtr);
      return ret;
    } 
  }

  public double b_axis_range_offset {
    set {
      SwigRanger3PINVOKE.genistreamtraits__b_axis_range_offset_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.genistreamtraits__b_axis_range_offset_get(swigCPtr);
      return ret;
    } 
  }

  public string b_axis_range_min {
    set {
      SwigRanger3PINVOKE.genistreamtraits__b_axis_range_min_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__b_axis_range_min_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string b_axis_range_max {
    set {
      SwigRanger3PINVOKE.genistreamtraits__b_axis_range_max_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__b_axis_range_max_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string b_axis_range_missing {
    set {
      SwigRanger3PINVOKE.genistreamtraits__b_axis_range_missing_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__b_axis_range_missing_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int b_axis_range_missing_value {
    set {
      SwigRanger3PINVOKE.genistreamtraits__b_axis_range_missing_value_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__b_axis_range_missing_value_get(swigCPtr);
      return ret;
    } 
  }

  public double c_axis_range_scale {
    set {
      SwigRanger3PINVOKE.genistreamtraits__c_axis_range_scale_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.genistreamtraits__c_axis_range_scale_get(swigCPtr);
      return ret;
    } 
  }

  public double c_axis_range_offset {
    set {
      SwigRanger3PINVOKE.genistreamtraits__c_axis_range_offset_set(swigCPtr, value);
    } 
    get {
      double ret = SwigRanger3PINVOKE.genistreamtraits__c_axis_range_offset_get(swigCPtr);
      return ret;
    } 
  }

  public int c_axis_range_min {
    set {
      SwigRanger3PINVOKE.genistreamtraits__c_axis_range_min_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__c_axis_range_min_get(swigCPtr);
      return ret;
    } 
  }

  public int c_axis_range_max {
    set {
      SwigRanger3PINVOKE.genistreamtraits__c_axis_range_max_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__c_axis_range_max_get(swigCPtr);
      return ret;
    } 
  }

  public string c_axis_range_missing {
    set {
      SwigRanger3PINVOKE.genistreamtraits__c_axis_range_missing_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__c_axis_range_missing_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int c_axis_range_missing_value {
    set {
      SwigRanger3PINVOKE.genistreamtraits__c_axis_range_missing_value_set(swigCPtr, value);
    } 
    get {
      int ret = SwigRanger3PINVOKE.genistreamtraits__c_axis_range_missing_value_get(swigCPtr);
      return ret;
    } 
  }

  public string unit {
    set {
      SwigRanger3PINVOKE.genistreamtraits__unit_set(swigCPtr, value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.genistreamtraits__unit_get(swigCPtr);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public genistreamtraits_() : this(SwigRanger3PINVOKE.new_genistreamtraits_(), true) {
  }

}

}
