//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {

/// <summary>双曝光中 Missing data 的处理选项。 Missing data processing mode.</summary>
public enum HDR_missingDataMode {
  ///  使能双曝光。 Enable dual-exposure
  Pick_Long_Exposure = 0,
  ///  不处理图像。 No changing original image
  Pick_Missing_Data
}

}
