//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>图像的基本信息。 struct of output images information.</summary>

public class ImgInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImgInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImgInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImgInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImgInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_ImgInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ImgInfo() : this(SwigRanger3PINVOKE.new_ImgInfo(), true) {
  }

  ///  未标定的高度数据信息。		Range Information
  public RangeInfo m_RI {
    set {
      SwigRanger3PINVOKE.ImgInfo_m_RI_set(swigCPtr, RangeInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SwigRanger3PINVOKE.ImgInfo_m_RI_get(swigCPtr);
      RangeInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new RangeInfo(cPtr, false);
      return ret;
    } 
  }

  ///  感光元件的基本信息。		Sensor Information
  public SensoInfo m_SI {
    set {
      SwigRanger3PINVOKE.ImgInfo_m_SI_set(swigCPtr, SensoInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SwigRanger3PINVOKE.ImgInfo_m_SI_get(swigCPtr);
      SensoInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new SensoInfo(cPtr, false);
      return ret;
    } 
  }

  ///  标定的高度数据信息。		Calibration Information
  public CalibInfo m_CI {
    set {
      SwigRanger3PINVOKE.ImgInfo_m_CI_set(swigCPtr, CalibInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SwigRanger3PINVOKE.ImgInfo_m_CI_get(swigCPtr);
      CalibInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new CalibInfo(cPtr, false);
      return ret;
    } 
  }

  ///  结构化的编码器信息。		ChunkInfo
  public SWIGTYPE_p_VecT_Ranger3LineMetadata_t m_ChunkData {
    set {
      SwigRanger3PINVOKE.ImgInfo_m_ChunkData_set(swigCPtr, SWIGTYPE_p_VecT_Ranger3LineMetadata_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SwigRanger3PINVOKE.ImgInfo_m_ChunkData_get(swigCPtr);
      SWIGTYPE_p_VecT_Ranger3LineMetadata_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_VecT_Ranger3LineMetadata_t(cPtr, false);
      return ret;
    } 
  }

  ///  Image ID
  public ulong m_id {
    set {
      SwigRanger3PINVOKE.ImgInfo_m_id_set(swigCPtr, value);
    } 
    get {
      ulong ret = SwigRanger3PINVOKE.ImgInfo_m_id_get(swigCPtr);
      return ret;
    } 
  }

}

}
