//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>输出图像 Class of output images.</summary>

public class ImgT : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImgT(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImgT obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImgT obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImgT() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_ImgT(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    // 重载 == 运算符
    public static bool operator ==(ImgT left, ImgT right)
    {
        // 1. 先处理空值
        if (object.ReferenceEquals(left, null))
            return object.ReferenceEquals(right, null);
        if (object.ReferenceEquals(right, null))
            return false;

        // 2. 调用 IsEqual 方法比较内容
        return left.IsEqual(right);
    }

    // 重载 != 运算符
    public static bool operator !=(ImgT left, ImgT right)
    {
        return !(left == right);
    }

    // 配套重写 Equals 和 GetHashCode，是规范要求，也能让 Assert.AreEqual 工作
    public override bool Equals(object obj)
    {
        return obj is ImgT other && this.IsEqual(other);
    }

    public override int GetHashCode()
    {
        // 简单返回基类哈希，或者根据内部数据计算
        return base.GetHashCode();
    }


    /// <summary>
    /// 自动将指针转换为byte数组（长度=row*col）。
    /// 您需要确保您输入的 dn 和返回的数据类型是匹配的。否则，将返回 null。
    /// </summary>
    public unsafe byte[] getDataByte(DataNames dn, uint col) 
    {
        System.IntPtr ptr = getDataByte_protected(dn);
        if (ptr == System.IntPtr.Zero)
        {
            return null;  // 返回空
        }
        var row = get_rows();
        int len = (int)(row * col);
        byte[] arr = new byte[len];

        fixed (byte* pDest = arr)
        {
            System.Buffer.MemoryCopy(
                (void*)ptr,
                pDest,
                len,           // byte 每个元素 1 字节
                len
            );
        }
        return arr;
    }

    /// <summary>
    /// 自动将指针转换为ushort数组（长度=row*col）。
    /// 您需要确保您输入的 dn 和返回的数据类型是匹配的。否则，将返回 null。
    /// </summary>
    public unsafe ushort[] getDataWord(DataNames dn, uint col) 
    {
        System.IntPtr ptr = getDataWord_protected(dn);
        if (ptr == System.IntPtr.Zero)
        {
            return null;  // 返回空
        }

        var row = get_rows();
        int len = (int)(row * col);
        ushort[] arr = new ushort[len];

        fixed (ushort* pDest = arr)
        {
            System.Buffer.MemoryCopy(
                (void*)ptr,    // 源指针
                pDest,          // 目标数组
                len * 2,        // 最大字节数
                len * 2         // 要复制的字节数
            );
        }
        return arr;
    }

    /// <summary>
    /// 自动将指针转换为float数组（长度=row*col）。
    /// 您需要确保您输入的 dn 和返回的数据类型是匹配的。否则，将返回 null。
    /// </summary>
    public unsafe float[] getDataFloat(DataNames dn, uint col) 
    {
        System.IntPtr ptr = getDataFloat_protected(dn);
        if (ptr == System.IntPtr.Zero)
        {
            return null;  // 返回空
        }
        var row = get_rows();
        int len = (int)(row * col);
        float[] arr = new float[len];

        fixed (float* pDest = arr)
        {
            System.Buffer.MemoryCopy(
                (void*)ptr,
                pDest,
                len * 4,       // float 每个元素 4 字节
                len * 4
            );
        }
        return arr;
    }


    /// <summary>
    /// 自动将指针转换为uint数组（长度=row*5）。
    /// 您需要确保您输入的 dn 和返回的数据类型是匹配的。否则，将返回 null。
    /// </summary>
    public unsafe uint[] getDataMark()
    {
        System.IntPtr ptr = getDataMark_protected();
        if (ptr == System.IntPtr.Zero)
        {
            return null;  // 返回空
        }
        var row = get_rows();
        int len = (int)(row * 5); // ChunkData 长度 5 个 uint32_t
        uint[] arr = new uint[len];
        // System.Runtime.InteropServices.Marshal.Copy(ptr, arr, 0, len);
        // return arr;

        fixed (uint* pDest = arr)
        {
            System.Buffer.MemoryCopy(
                (void*)ptr,    // 源指针
                pDest,          // 目标数组
                len * 4,        // 最大字节数
                len * 4         // 要复制的字节数
            );
        }
        return arr;
    }


  public ImgT() : this(SwigRanger3PINVOKE.new_ImgT__SWIG_0(), true) {
  }

  public ImgT(string path, double scaleY) : this(SwigRanger3PINVOKE.new_ImgT__SWIG_1(path, scaleY), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public ImgT(ImgT img) : this(SwigRanger3PINVOKE.new_ImgT__SWIG_2(ImgT.getCPtr(img)), true) {
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>将数据的枚举名转化为对应的字符串。Convert DataNames to its corresponding string name.</summary>
  /// Title: 数据枚举名和对应字符串的对应表    The list of enum DataNames and corresponding string name.
  /// 		{ DN::INV			, "INVALID" },
  /// 		{ DN::SEN			, "SENSOR" },
  ///
  /// 		{ DN::RAN			, "ComponentSelector_Range_RegionSelector_Scan3dExtraction1"			},
  /// 		{ DN::REF			, "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1"		},
  /// 		{ DN::SCA_8			, "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1" },
  /// 		{ DN::SCA_16		, "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1" },
  /// 		{ DN::MAR			, "Encoder_information"			},
  /// 		{ DN::RAN_CAL		, "ComponentSelector_Range_RegionSelector_Scan3dExtraction1_CAL"		},
  /// 		{ DN::RAN_CAL_16	, "ComponentSelector_Range_RegionSelector_Scan3dExtraction1_CAL_16"  	},
  /// 		{ DN::REF_CAL		, "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1_CAL"	},
  /// 		{ DN::REF_CAL_F		, "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1_CAL_F"},
  /// 		{ DN::SCA_8_CAL		, "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1_CAL" },
  /// 		{ DN::SCA_16_CAL	, "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1_CAL"},
  ///
  /// 		{ DN::RAN2			, "ComponentSelector_Range_RegionSelector_Scan3dExtraction2"			},
  /// 		{ DN::REF2			, "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction2"		},
  /// 		{ DN::SCA2_8		, "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2" },
  /// 		{ DN::SCA2_16		, "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2"	},
  /// 		{ DN::RAN2_CAL		, "ComponentSelector_Range_RegionSelector_Scan3dExtraction2_CAL"		},
  /// 		{ DN::REF2_CAL		, "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction2_CAL"	},
  /// 		{ DN::SCA2_8_CAL	, "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2_CAL" },
  /// 		{ DN::SCA2_16_CAL	, "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2_CAL"},
  ///
  /// 		{ DN::RAN_X	        , "RangeX_Calibration_Only_Without_Rectification"						},
  /// 		{ DN::RAN_X_16	    , "16_Byte_RangeX_Calibration_Only_Without_Rectification"				},
  ///
  public static string DN2Str(DataNames _dn) {
    string ret = SwigRanger3PINVOKE.ImgT_DN2Str((int)_dn);
    return ret;
  }

  /// <summary>将相应的字符串转化为数据的枚举名。Convert string name to its corresponding DataNames.</summary>
  /// Title: 对应字符串和数据枚举名的对应表    The list of string name and corresponding enum DataNames.
  /// 		{ "INVALID"																	, DN::INV		},
  /// 		{ "SENSOR"																	, DN::SEN		},
  ///
  /// 		{ "ComponentSelector_Range_RegionSelector_Scan3dExtraction1"				, DN::RAN		},
  /// 		{ "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1"			, DN::REF		},
  /// 		{ "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1"		, DN::SCA_8		},
  /// 		{ "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1"		, DN::SCA_16	},
  /// 		{ "ComponentSelector_Range_RegionSelector_Scan3dExtraction1_CAL"			, DN::RAN_CAL	},
  /// 		{ "ComponentSelector_Range_RegionSelector_Scan3dExtraction1_CAL_16"			, DN::RAN_CAL_16},
  /// 		{ "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1_CAL"		, DN::REF_CAL	},
  /// 		{ "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1_CAL_F"	, DN::REF_CAL_F },
  /// 		{ "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1_CAL"	, DN::SCA_8_CAL	},
  /// 		{ "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction1_CAL"	, DN::SCA_16_CAL},
  ///
  /// 		{ "ComponentSelector_Range_RegionSelector_Scan3dExtraction2"				, DN::RAN2		},
  /// 		{ "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction2"			, DN::REF2		},
  /// 		{ "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2"		, DN::SCA2_8	},
  /// 		{ "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2"		, DN::SCA2_16	},
  /// 		{ "ComponentSelector_Range_RegionSelector_Scan3dExtraction2_CAL"			, DN::RAN2_CAL	},
  /// 		{ "ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction2_CAL"		, DN::REF2_CAL	},
  /// 		{ "8_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2_CAL"	, DN::SCA2_8_CAL },
  /// 		{ "16_Byte_ComponentSelector_Scatter_RegionSelector_Scan3dExtraction2_CAL"	, DN::SCA2_16_CAL},
  ///
  /// 		{ "RangeX_Calibration_Only_Without_Rectification"							, DN::RAN_X		},
  /// 		{ "16_Byte_RangeX_Calibration_Only_Without_Rectification"					, DN::RAN_X_16	}
  ///
  public static DataNames Str2DN(string _str) {
    DataNames ret = (DataNames)SwigRanger3PINVOKE.ImgT_Str2DN(_str);
    
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
}

  /// <summary>获得当前所有有效数据的枚举名列表。</summary>
  public DataNamesVector getAvalibleDataNames() {
    DataNamesVector ret = new DataNamesVector(SwigRanger3PINVOKE.ImgT_getAvalibleDataNames(swigCPtr), true);
    return ret;
  }

  /// <summary>获得当前所有有效（未标定）数据的枚举名列表。</summary>
  /// <summary>获得当前所有有效（未定）数据的枚举名列表。</summary>
  /// <summary>图像数据宽度，注意，当图像中有多个图像组时候，得到的结果仅为Range图像的原始大小。数据类型的名字定义，详见：enum DataNames</summary>
  /// 宽度为
  /// 宽度为【ROI 宽度】的组件：SEN,	RAN,REF,SCA_8,SCA_16,RAN2,REF2,SCA2_8,SCA2_16,RAN_X,RAN_X_16,
  /// 宽度为【5】 的组件：MAR,
  /// 宽度为【RectificationWidth（用户定义的梯形校正插值宽度）】的组件：RAN_CAL,RAN_CAL_16,REF_CAL,REF_CAL_F,SCA_8_CAL,SCA_16_CAL,RAN2_CAL,REF2_CAL,SCA2_8_CAL,SCA2_16_CAL,
  /// 宽度为【5120】的组件：	WHITE,R,G,B,
  /// <summary>图像数据宽度，注意，当图像中有多个图像组时候，得到的结果仅为Range图像的原始大小。当使用 in-device 标定时，返回标定后的图像大小；当使用 in-pc 标定时，相机返回的是未标定图像，那么这里返回的是 DataName::RAN 的宽度；当使用 in-pc 标定时，经过标定后的图像，它的宽度是由用户决定的，见 InitCalibration() 的 RectificationWidth 参数；当使用 in-pc 标定时，经过标定后的彩色图像，它的宽度是由用户决定的，见 InitCalibrationColor() 的 RectificationWidth 参数；</summary>
  public uint get_cols() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_get_cols__SWIG_0(swigCPtr);
    
    return ret;
}

  /// <summary>获得指定的图像数据高度。</summary>
  public uint get_rows() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_get_rows__SWIG_0(swigCPtr);
    
    return ret;
}

  public SensoInfo getSensor_info() {
    SensoInfo ret = new SensoInfo(SwigRanger3PINVOKE.ImgT_getSensor_info(swigCPtr), false);
    return ret;
  }

  public RangeInfo getRange_info() {
    RangeInfo ret = new RangeInfo(SwigRanger3PINVOKE.ImgT_getRange_info(swigCPtr), false);
    return ret;
  }

  public CalibInfo getCalibration_info() {
    CalibInfo ret = new CalibInfo(SwigRanger3PINVOKE.ImgT_getCalibration_info(swigCPtr), false);
    return ret;
  }

  /// <summary>获得每个剖面的编码器信息。Get encoder information of each profile.</summary>
  /// - timestamp           uint64_t   单位是纳秒，表示取剖面时相机内部时钟的时间戳。
  ///
  /// - encoderValue        int32_t    编码器旋转，该值会记录相应的脉冲数。当编码器反转，计数值会减少相应的脉冲数。该值可能是负数。
  ///
  /// - overtriggerCount    uint8_t    在获取一个剖面还未完成时，如果接收到获取下一个剖面的触发信号，该值为1，否则为0。 1 if a line trigger has been requested before the sensor was actually ready for a new trigger.
  ///
  /// - frameTriggerActive  bool       在获取图像还未完成时，如果 frame trigger pin (IO pin 1) 是高电平，该值为1，否则为0。 1 if frame trigger pin (IO pin 1) is high, otherwise 0.
  ///
  /// - lineTriggerActive   bool       在获取一个剖面还未完成时，如果 line trigger pin (IO pin 2) 是高电平，该值为1，否则为0。 1 if line trigger pin (IO pin 2) is high, otherwise 0.
  ///
  /// - encoderResetActive  bool       1 if Encoder Reset (IO pin 3) is high, otherwise 0.
  ///
  /// - encoderA            bool       Value 0 (for low) or 1 (for high) at encoder channel A.
  ///
  /// - encoderB            bool       Value 0 (for low) or 1 (for high) at encoder channel B.
  public SWIGTYPE_p_VecT_Ranger3LineMetadata_t get_ChunkInfo() {
    SWIGTYPE_p_VecT_Ranger3LineMetadata_t ret = new SWIGTYPE_p_VecT_Ranger3LineMetadata_t(SwigRanger3PINVOKE.ImgT_get_ChunkInfo(swigCPtr), false);
    return ret;
  }

  /// <summary>0初始。相机停止后重置。Start from 0. Reset when camera stop.</summary>
  public ulong get_ID() {
    ulong ret = SwigRanger3PINVOKE.ImgT_get_ID(swigCPtr);
    return ret;
  }

  /// <summary>无数据指针返回 false.Return false if no data pointer.</summary>
  public bool isEmpty() {
    bool ret = SwigRanger3PINVOKE.ImgT_isEmpty(swigCPtr);
    return ret;
  }

  /// <summary>如果没有指定的数据则返回 false.Return false if no such data pointer.</summary>
  public bool has(DataNames _name) {
    bool ret = SwigRanger3PINVOKE.ImgT_has(swigCPtr, (int)_name);
    return ret;
  }

  /// <summary>无编码器信息返回 false.Return false if no encoder information.</summary>
  public bool has_ChunkInfo() {
    bool ret = SwigRanger3PINVOKE.ImgT_has_ChunkInfo(swigCPtr);
    return ret;
  }

  public void printInfo() {
    SwigRanger3PINVOKE.ImgT_printInfo(swigCPtr);
  }

  /// <summary>仅测试用。读取图形的基本信息。</summary>
  public string collectInfo() {
    string ret = SwigRanger3PINVOKE.ImgT_collectInfo(swigCPtr);
    return ret;
  }

  /// <summary>释放标定资源（静态资源）。</summary>
  public static bool DeleteCalibration(int handle) {
    bool ret = SwigRanger3PINVOKE.ImgT_DeleteCalibration(handle);
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile, int removeLastNRows, bool doRectify, double rectificationSpread, int rawRangeWidth, int rectificationWidth, RectMethod rectMethod, int numberOfThreads) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_0(swigCPtr, calibrationHandle, calibrationFile, removeLastNRows, doRectify, rectificationSpread, rawRangeWidth, rectificationWidth, (int)rectMethod, numberOfThreads), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile, int removeLastNRows, bool doRectify, double rectificationSpread, int rawRangeWidth, int rectificationWidth, RectMethod rectMethod) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_1(swigCPtr, calibrationHandle, calibrationFile, removeLastNRows, doRectify, rectificationSpread, rawRangeWidth, rectificationWidth, (int)rectMethod), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile, int removeLastNRows, bool doRectify, double rectificationSpread, int rawRangeWidth, int rectificationWidth) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_2(swigCPtr, calibrationHandle, calibrationFile, removeLastNRows, doRectify, rectificationSpread, rawRangeWidth, rectificationWidth), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile, int removeLastNRows, bool doRectify, double rectificationSpread, int rawRangeWidth) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_3(swigCPtr, calibrationHandle, calibrationFile, removeLastNRows, doRectify, rectificationSpread, rawRangeWidth), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile, int removeLastNRows, bool doRectify, double rectificationSpread) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_4(swigCPtr, calibrationHandle, calibrationFile, removeLastNRows, doRectify, rectificationSpread), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile, int removeLastNRows, bool doRectify) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_5(swigCPtr, calibrationHandle, calibrationFile, removeLastNRows, doRectify), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile, int removeLastNRows) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_6(swigCPtr, calibrationHandle, calibrationFile, removeLastNRows), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImgT ApplyCalibration(int calibrationHandle, string calibrationFile) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibration__SWIG_7(swigCPtr, calibrationHandle, calibrationFile), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>释放标定资源（静态）。</summary>
  public static bool DeleteCalibrationColor(int handle) {
    bool ret = SwigRanger3PINVOKE.ImgT_DeleteCalibrationColor(handle);
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride, double rectificationSpread, int rawColoreResizedWidth, int rectificationWidth, RectMethod rectMethod, int removeHeadNRows, bool doCalibration, int numberOfThreads) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_0(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride, rectificationSpread, rawColoreResizedWidth, rectificationWidth, (int)rectMethod, removeHeadNRows, doCalibration, numberOfThreads), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride, double rectificationSpread, int rawColoreResizedWidth, int rectificationWidth, RectMethod rectMethod, int removeHeadNRows, bool doCalibration) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_1(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride, rectificationSpread, rawColoreResizedWidth, rectificationWidth, (int)rectMethod, removeHeadNRows, doCalibration), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride, double rectificationSpread, int rawColoreResizedWidth, int rectificationWidth, RectMethod rectMethod, int removeHeadNRows) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_2(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride, rectificationSpread, rawColoreResizedWidth, rectificationWidth, (int)rectMethod, removeHeadNRows), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride, double rectificationSpread, int rawColoreResizedWidth, int rectificationWidth, RectMethod rectMethod) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_3(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride, rectificationSpread, rawColoreResizedWidth, rectificationWidth, (int)rectMethod), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride, double rectificationSpread, int rawColoreResizedWidth, int rectificationWidth) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_4(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride, rectificationSpread, rawColoreResizedWidth, rectificationWidth), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride, double rectificationSpread, int rawColoreResizedWidth) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_5(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride, rectificationSpread, rawColoreResizedWidth), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride, double rectificationSpread) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_6(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride, rectificationSpread), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC, int colorInterpolationStride) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_7(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC, colorInterpolationStride), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows, bool doFCC) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_8(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows, doFCC), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile, int removeLastNRows) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_9(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile, removeLastNRows), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>初始化的彩色标定（申请静态资源）。当无需继续使用后，请调用 DeleteCalibrationColor 释放资源。</summary>
  /// 			enum RectMethod
  /// 			{
  /// 				Mean = 0,
  /// 				Top,
  /// 				Bottom,
  /// 				DARKEST,
  /// 				BRIGHTEST,
  /// 				NOT_DO,
  /// 			};
  public ImgT ApplyCalibrationColor(int colorCalibrateAlignHandle, string calibrationFile, string colorFile) {
    ImgT ret = new ImgT(SwigRanger3PINVOKE.ImgT_ApplyCalibrationColor__SWIG_10(swigCPtr, colorCalibrateAlignHandle, calibrationFile, colorFile), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>将目标图像 (src) 拼接到当前图像 (this) 的尾后，并且返回合并后数据，修改原始图像。对 src 和 this 的要求如下：- 假如 src[RAN, REF, R, G, B], this[RAN, REF, G, WHITE]，那么返回的图像只含有[RAN, REF, G]。- 假如 src[RAN, REF, R, G, B]的 Height 是 1000, this[RAN, REF] 的 height 是 500，那么返回的图像 height 是 1500。- 假如 src[RAN, REF, R, G, B]中 RAN 和 REF 的 width 是 2560，RGB 的 width 是 5120， this[RAN, REF]的width是2560，那么返回的图像[RAN, REF]的width是2560。- 假如 src[RAN, REF, R, G, B]中 RAN 和 REF 的 width 是 1280，RGB 的 width 是 5120， this[RAN, REF]的width是2560，那么返回空图像。</summary>
  public void Append(ImgT src) {
    SwigRanger3PINVOKE.ImgT_Append(swigCPtr, ImgT.getCPtr(src));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__vectorT_SickCam__ImgT_t Divide(int parts) {
    SWIGTYPE_p_std__vectorT_SickCam__ImgT_t ret = new SWIGTYPE_p_std__vectorT_SickCam__ImgT_t(SwigRanger3PINVOKE.ImgT_Divide(swigCPtr, parts), true);
    return ret;
  }

  /// <summary>读取 ICON 图像文件。load image data from Icon file.</summary>
  /// 如果该图像是使用 WORD 表示标定后的 Region 图像，读取函数会将其转化成 FLOAT 类型，并体现为 DataNames::RAN_CAL
  public bool loadFromIconFile(string path, double resolutonY, double resolutonZ, bool convertRangeToFloat) {
    bool ret = SwigRanger3PINVOKE.ImgT_loadFromIconFile__SWIG_0(swigCPtr, path, resolutonY, resolutonZ, convertRangeToFloat);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>读取 ICON 图像文件。load image data from Icon file.</summary>
  /// 如果该图像是使用 WORD 表示标定后的 Region 图像，读取函数会将其转化成 FLOAT 类型，并体现为 DataNames::RAN_CAL
  public bool loadFromIconFile(string path, double resolutonY, double resolutonZ) {
    bool ret = SwigRanger3PINVOKE.ImgT_loadFromIconFile__SWIG_1(swigCPtr, path, resolutonY, resolutonZ);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>读取 ICON 图像文件。load image data from Icon file.</summary>
  /// 如果该图像是使用 WORD 表示标定后的 Region 图像，读取函数会将其转化成 FLOAT 类型，并体现为 DataNames::RAN_CAL
  public bool loadFromIconFile(string path, double resolutonY) {
    bool ret = SwigRanger3PINVOKE.ImgT_loadFromIconFile__SWIG_2(swigCPtr, path, resolutonY);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>保存激光线图像。相机若不处于激光线模式，则返回 false 。成功保存，则返回 true。</summary>
  public bool SaveSensorImageToIconFile(string path, bool byFStream) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveSensorImageToIconFile__SWIG_0(swigCPtr, path, byFStream);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>保存激光线图像。相机若不处于激光线模式，则返回 false 。成功保存，则返回 true。</summary>
  public bool SaveSensorImageToIconFile(string path) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveSensorImageToIconFile__SWIG_1(swigCPtr, path);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>保存未标定的原始图像。相机若不处于高度图模式，则返回 false 。成功保存，则返回 true。</summary>
  public bool SaveRawImagesToIconFile(string path, bool withChunkData, bool byFStream) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveRawImagesToIconFile__SWIG_0(swigCPtr, path, withChunkData, byFStream);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>保存未标定的原始图像。相机若不处于高度图模式，则返回 false 。成功保存，则返回 true。</summary>
  public bool SaveRawImagesToIconFile(string path, bool withChunkData) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveRawImagesToIconFile__SWIG_1(swigCPtr, path, withChunkData);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>保存标定后的图像。相机若不处于高度图模式且启用标定功能，则返回 false 。成功保存，则返回 true。</summary>
  public bool SaveCalibratedImagesToIconFile(string path, bool withChunkData, bool byFStream) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveCalibratedImagesToIconFile__SWIG_0(swigCPtr, path, withChunkData, byFStream);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>保存标定后的图像。相机若不处于高度图模式且启用标定功能，则返回 false 。成功保存，则返回 true。</summary>
  public bool SaveCalibratedImagesToIconFile(string path, bool withChunkData) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveCalibratedImagesToIconFile__SWIG_1(swigCPtr, path, withChunkData);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用】（此函数已经弃用，请见 Demo_ImgT_convert_to_point_cloud.cpp）保存为 txt 点云。Save data as point cloud format, txt.data example:	xValue1, yValue1, zValue1,	xValue2, yValue2, zValue2,	...	</summary>
  ///
  ///
  ///
  /// 仅标定后的数据可以调用该函数。
  ///
  ///
  /// Calibrated Data only!
  public bool SaveCalibratedDataToPointCloud(string pathconst, bool please_do_not_use_it_any_more) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveCalibratedDataToPointCloud__SWIG_0(swigCPtr, pathconst, please_do_not_use_it_any_more);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用】（此函数已经弃用，请见 Demo_ImgT_convert_to_point_cloud.cpp）保存为 txt 点云。Save data as point cloud format, txt.data example:	xValue1, yValue1, zValue1,	xValue2, yValue2, zValue2,	...	</summary>
  ///
  ///
  ///
  /// 仅标定后的数据可以调用该函数。
  ///
  ///
  /// Calibrated Data only!
  public bool SaveCalibratedDataToPointCloud(string pathconst) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveCalibratedDataToPointCloud__SWIG_1(swigCPtr, pathconst);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 get_cols(void)</summary>
  public uint get_cols(DataNames please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_get_cols__SWIG_1(swigCPtr, (int)please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_rows(void)</summary>
  public uint get_rows(DataNames please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_get_rows__SWIG_1(swigCPtr, (int)please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_cols(void)</summary>
  public uint getS_cols(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_cols__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_cols(void)</summary>
  public uint getS_cols() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_cols__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_rows(void)</summary>
  public uint getS_rows(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_rows__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_rows(void)</summary>
  public uint getS_rows() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_rows__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getSensor_info()</summary>
  public uint getS_OffsetX(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_OffsetX__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getSensor_info()</summary>
  public uint getS_OffsetX() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_OffsetX__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getSensor_info()</summary>
  public uint getS_OffsetY(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_OffsetY__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getSensor_info()</summary>
  public uint getS_OffsetY() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getS_OffsetY__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_cols()</summary>
  public uint getR_cols(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_cols__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_cols()</summary>
  public uint getR_cols() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_cols__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_rows()</summary>
  public uint getR_rows(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_rows__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_rows()</summary>
  public uint getR_rows() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_rows__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info().aoiOffsetX</summary>
  public uint getR_aoiOffsetX(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiOffsetX__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info().aoiOffsetX</summary>
  public uint getR_aoiOffsetX() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiOffsetX__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info().aoiOffsetY</summary>
  public uint getR_aoiOffsetY(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiOffsetY__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info().aoiOffsetY</summary>
  public uint getR_aoiOffsetY() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiOffsetY__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public uint getR_aoiHeight(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiHeight__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public uint getR_aoiHeight() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiHeight__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public uint getR_aoiWidth(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiWidth__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public uint getR_aoiWidth() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getR_aoiWidth__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public SWIGTYPE_p_geniranger__RangeAxis getR_RangeAxis(int please_do_not_use_it_any_more) {
    SWIGTYPE_p_geniranger__RangeAxis ret = new SWIGTYPE_p_geniranger__RangeAxis(SwigRanger3PINVOKE.ImgT_getR_RangeAxis__SWIG_0(swigCPtr, please_do_not_use_it_any_more), false);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public SWIGTYPE_p_geniranger__RangeAxis getR_RangeAxis() {
    SWIGTYPE_p_geniranger__RangeAxis ret = new SWIGTYPE_p_geniranger__RangeAxis(SwigRanger3PINVOKE.ImgT_getR_RangeAxis__SWIG_1(swigCPtr), false);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public double getR_ScaleZ(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getR_ScaleZ__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getRange_info()</summary>
  public double getR_ScaleZ() {
    double ret = SwigRanger3PINVOKE.ImgT_getR_ScaleZ__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 get_cols()</summary>
  public uint getC_cols(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getC_cols__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_cols()</summary>
  public uint getC_cols() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getC_cols__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_rows()</summary>
  public uint getC_rows(int please_do_not_use_it_any_more) {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getC_rows__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 get_rows()</summary>
  public uint getC_rows() {
    uint ret = (uint)SwigRanger3PINVOKE.ImgT_getC_rows__SWIG_1(swigCPtr);
    
    return ret;
}

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_offsetX(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_offsetX__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_offsetX() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_offsetX__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_offsetY(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_offsetY__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_offsetY() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_offsetY__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_scaleX(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_scaleX__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_scaleX() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_scaleX__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_scaleY(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_scaleY__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_scaleY() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_scaleY__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_lower_bound_x(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_lower_bound_x__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_lower_bound_x() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_lower_bound_x__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_upper_bound_x(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_upper_bound_x__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_upper_bound_x() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_upper_bound_x__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_lower_bound_r(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_lower_bound_r__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_lower_bound_r() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_lower_bound_r__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_upper_bound_r(int please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.ImgT_getC_upper_bound_r__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用 getCalibration_info()</summary>
  public double getC_upper_bound_r() {
    double ret = SwigRanger3PINVOKE.ImgT_getC_upper_bound_r__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用以下的函数替代。bool SaveSensorImageToIconFile      (string path)	bool SaveRawImagesToIconFile	      (string path, bool withChunkData)	bool SaveCalibratedImagesToIconFile (string path, bool withChunkData)	保存为 ICON 格式的图像数据。Save data as SICK icon format.</summary>
  /// components 之中不可以混合原始数据和标定后数据。
  ///
  ///
  ///
  ///
  /// &lt;code&gt;    		SaveToIconFile("D:/img_sen", { DataNames::SEN }, false); // only sensor is allowed.
  ///     		SaveToIconFile("D:/img_raw", { DataNames::RAN, DataNames::REF, DataNames::SCA_16, DataNames::MAR }, false); // SCA_8 and SCA_16 are mutually exclusive.
  ///     		SaveToIconFile("D:/img_cal", { DataNames::RAN_CAL, DataNames::REF_CAL, DataNames::SCA_16_CAL, DataNames::MAR  }, true); // MAR is the encoder data, can be saved together with both.
  ///
  ///     Wrong example:
  ///     		SaveToIconFile("D:/img_cal", { DataNames::RAN, DataNames::REF, DataNames::RAN_CAL, DataNames::REF_CAL }, true); // Do not mix them!&lt;/code&gt;
  public bool SaveToIconFile(string please_do_not_use_it_any_more, DataNamesVector components, bool is_calibrated) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveToIconFile__SWIG_0(swigCPtr, please_do_not_use_it_any_more, DataNamesVector.getCPtr(components), is_calibrated);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用】，请使用以下的函数替代。bool SaveSensorImageToIconFile      (string path)	bool SaveRawImagesToIconFile	      (string path, bool withChunkData)	bool SaveCalibratedImagesToIconFile (string path, bool withChunkData)	保存为 ICON 格式的图像数据。Save data as SICK icon format.</summary>
  public bool SaveToIconFile(string please_do_not_use_it_any_more, DataNamesVector components) {
    bool ret = SwigRanger3PINVOKE.ImgT_SaveToIconFile__SWIG_1(swigCPtr, please_do_not_use_it_any_more, DataNamesVector.getCPtr(components));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  ///  Please do not modify it! Used in online grabbing. if (m_previousImageID+1 != get_ID()), images lost.
  public ulong m_previousImageID {
    set {
      SwigRanger3PINVOKE.ImgT_m_previousImageID_set(swigCPtr, value);
    } 
    get {
      ulong ret = SwigRanger3PINVOKE.ImgT_m_previousImageID_get(swigCPtr);
      return ret;
    } 
  }

  ///  the image data information. The chunkdata is inside this struct.
  public ImgInfo m_info {
    set {
      SwigRanger3PINVOKE.ImgT_m_info_set(swigCPtr, ImgInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SwigRanger3PINVOKE.ImgT_m_info_get(swigCPtr);
      ImgInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new ImgInfo(cPtr, false);
      return ret;
    } 
  }

  public System.IntPtr getDataByte_protected(DataNames dn) {
    System.IntPtr ret = (System.IntPtr)SwigRanger3PINVOKE.ImgT_getDataByte_protected(swigCPtr, (int)dn);
    
    return ret;
}

  public System.IntPtr getDataWord_protected(DataNames dn) {
    System.IntPtr ret = (System.IntPtr)SwigRanger3PINVOKE.ImgT_getDataWord_protected(swigCPtr, (int)dn);
    
    return ret;
}

  public System.IntPtr getDataFloat_protected(DataNames dn) {
    System.IntPtr ret = (System.IntPtr)SwigRanger3PINVOKE.ImgT_getDataFloat_protected(swigCPtr, (int)dn);
    
    return ret;
}

  public System.IntPtr getDataMark_protected() {
    System.IntPtr ret = (System.IntPtr)SwigRanger3PINVOKE.ImgT_getDataMark_protected(swigCPtr);
    
    return ret;
}

  public bool IsEqual(ImgT other) {
    bool ret = SwigRanger3PINVOKE.ImgT_IsEqual(swigCPtr, ImgT.getCPtr(other));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// &lt;summary&gt;
  /// 深度拷贝赋值
  /// &lt;summary&gt;
  public void DeepCopy(ImgT other) {
    SwigRanger3PINVOKE.ImgT_DeepCopy(swigCPtr, ImgT.getCPtr(other));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

}

}
