//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>未标定的高度数据信息  Raw range data information.</summary>

public class RangeInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RangeInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RangeInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RangeInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RangeInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_RangeInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public RangeInfo() : this(SwigRanger3PINVOKE.new_RangeInfo(), true) {
  }

  public void fillXML_byDeviceParameters() {
    SwigRanger3PINVOKE.RangeInfo_fillXML_byDeviceParameters(swigCPtr);
  }

  ///  3D 图像宽度。 Width of range image.
  public uint cols {
    set {
      SwigRanger3PINVOKE.RangeInfo_cols_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.RangeInfo_cols_get(swigCPtr);
      return ret;
    } 
  }

  ///  3D 图像高度。 Height of range image.
  public uint rows {
    set {
      SwigRanger3PINVOKE.RangeInfo_rows_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.RangeInfo_rows_get(swigCPtr);
      return ret;
    } 
  }

  ///  在 sensor 上设置的 AOI 的左上 X 坐标，像素。[ICON | XML 参数]-&gt;["origin x"]。[相机参数]-&gt;[OffsetX_RegionSelector_Region1]。
  public uint aoiOffsetX {
    set {
      SwigRanger3PINVOKE.RangeInfo_aoiOffsetX_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.RangeInfo_aoiOffsetX_get(swigCPtr);
      return ret;
    } 
  }

  ///  在 sensor 上设置的 AOI 的左上 Y 坐标，像素。[ICON | XML 参数]-&gt;["origin z"]。[相机参数]-&gt;[OffsetY_RegionSelector_Region1]。
  public uint aoiOffsetY {
    set {
      SwigRanger3PINVOKE.RangeInfo_aoiOffsetY_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.RangeInfo_aoiOffsetY_get(swigCPtr);
      return ret;
    } 
  }

  ///  在 sensor 上设置的 AOI 的高度，像素。[ICON | XML 参数]-&gt;[("fov z2" + 1) / 16.0]。[相机参数]-&gt;[Height_RegionSelector_Region1]。
  public uint aoiHeight {
    set {
      SwigRanger3PINVOKE.RangeInfo_aoiHeight_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.RangeInfo_aoiHeight_get(swigCPtr);
      return ret;
    } 
  }

  ///  在 sensor 上设置的 AOI 的宽度，像素。[ICON | XML 参数]-&gt;["fov x1" - "fov x0" + 1]。[相机参数]-&gt;[Width_RegionSelector_Region1]。
  public uint aoiWidth {
    set {
      SwigRanger3PINVOKE.RangeInfo_aoiWidth_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.RangeInfo_aoiWidth_get(swigCPtr);
      return ret;
    } 
  }

  ///  3D 图像的 R 轴方向。激光竖直架设，R 就是 Z 轴。3D 图像的 R 轴对应于 sensor 上的 Y 轴。支持将 Y 轴取反。"STANDARD" 表示 sensor 上到下。
  public SWIGTYPE_p_geniranger__RangeAxis m_RangeAxis {
    set {
      SwigRanger3PINVOKE.RangeInfo_m_RangeAxis_set(swigCPtr, SWIGTYPE_p_geniranger__RangeAxis.getCPtr(value));
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_geniranger__RangeAxis ret = new SWIGTYPE_p_geniranger__RangeAxis(SwigRanger3PINVOKE.RangeInfo_m_RangeAxis_get(swigCPtr), true);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（左上，X 坐标），像素，始终为0。
  public float xml_fov_x0 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_x0_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_x0_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（右上，X 坐标），像素，aoiHeight - 1。
  public float xml_fov_x1 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_x1_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_x1_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（左下，X 坐标），像素，始终为0。
  public float xml_fov_x2 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_x2_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_x2_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（右下，X 坐标），像素，aoiWidth - 1。
  public float xml_fov_x3 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_x3_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_x3_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（左上，Y 坐标），像素，始终为1。
  public float xml_fov_z0 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_z0_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_z0_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（右上，Y 坐标），像素，aoiHeight * 16 - 1 。
  public float xml_fov_z1 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_z1_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_z1_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（左下，Y 坐标），像素，始终为1。
  public float xml_fov_z2 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_z2_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_z2_get(swigCPtr);
      return ret;
    } 
  }

  ///  [ICON | XML 参数] 在 sensor 上设置的 AOI 的矩形区参数（右下，Y 坐标），像素，aoiHeight * 16 - 1 。
  public float xml_fov_z3 {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_fov_z3_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_fov_z3_get(swigCPtr);
      return ret;
    } 
  }

  ///  在 sensor 上设置的 AOI 的左上 X 坐标，像素。[ICON | XML 参数]-&gt;["origin x"]。[相机参数]-&gt;[OffsetX_RegionSelector_Region1]。
  public float xml_origin_x {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_origin_x_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_origin_x_get(swigCPtr);
      return ret;
    } 
  }

  ///  提取激光线算法，在 sensor 图像的 X 坐标上的亚像素分辨率。始终为 1.0。
  public float xml_scale_x {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_scale_x_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_scale_x_get(swigCPtr);
      return ret;
    } 
  }

  ///  在 sensor 上设置的 AOI 的左上 Y 坐标，像素。[ICON | XML 参数]-&gt;["origin z"]。[相机参数]-&gt;[OffsetY_RegionSelector_Region1]。
  public float xml_origin_z {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_origin_z_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_origin_z_get(swigCPtr);
      return ret;
    } 
  }

  ///  提取激光线算法，在 sensor 图像的 Y 坐标上的亚像素分辨率。始终为 0.0625(=1/16.0)。[RangeAxis = "STANDARD"] 取正值，[RangeAxis = "REVERSE"] 取负值，
  public float xml_scale_z {
    set {
      SwigRanger3PINVOKE.RangeInfo_xml_scale_z_set(swigCPtr, value);
    } 
    get {
      float ret = SwigRanger3PINVOKE.RangeInfo_xml_scale_z_get(swigCPtr);
      return ret;
    } 
  }

}

}
