//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>每个 Ranger3 对应应该初始化为一个 Ranger3 的类对象。</summary>

public class Ranger3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Ranger3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Ranger3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Ranger3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Ranger3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_Ranger3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    /// <summary>
    /// 图像接收事件，当相机捕获到新图像时触发。参数：（image，r3）
    /// </summary>
    /// <param name="ImgT">捕获到的图像对象（不拥有内存所有权）</param>
    /// <param name="Ranger3">相机实例对象，用于访问相机相关方法</param>
    public event System.Action<ImgT, Ranger3> ImageReceived;
    
    /// <summary>
    /// 心跳丢失事件，当相机心跳丢失时触发。参数：（name，ip，mac，msg，userData）
    /// </summary>
    /// <param name="name">设备名称</param>
    /// <param name="ip">设备 IP 地址</param>
    /// <param name="mac">设备 MAC 地址</param>
    /// <param name="msg">心跳丢失原因</param>
    /// <param name="userData">用户自定义数据，在连接相机时传入</param>
    public event System.Action<string, string, string, string, Ranger3> HeartBeatLost;

    /// <summary>
    /// 心跳丢失事件，当相机心跳丢失时触发。参数：（name，ip，mac，msg，userData）
    /// </summary>
    /// <param name="name">设备名称</param>
    /// <param name="ip">设备 IP 地址</param>
    /// <param name="mac">设备 MAC 地址</param>
    /// <param name="msg">心跳丢失原因</param>
    /// <param name="userData">用户自定义数据，在连接相机时传入</param>
    public event System.Action<string, string, string, string, Ranger3> HeartBeatLost_ReconnectOK;
    
    /// <summary>
    /// 心跳丢失事件，当相机心跳丢失时触发。参数：（name，ip，mac，msg，userData）
    /// </summary>
    /// <param name="name">设备名称</param>
    /// <param name="ip">设备 IP 地址</param>
    /// <param name="mac">设备 MAC 地址</param>
    /// <param name="msg">心跳丢失原因</param>
    /// <param name="userData">用户自定义数据，在连接相机时传入</param>
    public event System.Action<string, string, string, string, Ranger3> HeartBeatLost_ReconnectFailed;




    
    // 非托管回调委托类型（必须是非泛型的，才能获取函数指针）
    [System.Runtime.InteropServices.UnmanagedFunctionPointer(System.Runtime.InteropServices.CallingConvention.Cdecl)]
    private delegate void ImageCallbackDelegate(System.IntPtr imgPtr, System.IntPtr r3Ptr);
    
    // 心跳丢失回调委托类型
    [System.Runtime.InteropServices.UnmanagedFunctionPointer(System.Runtime.InteropServices.CallingConvention.Cdecl)]
    private delegate void HeartBeatLostCallbackDelegate(
        System.IntPtr namePtr, System.IntPtr ipPtr, System.IntPtr macPtr, System.IntPtr msgPtr, System.IntPtr r3Ptr);
    
    // 保存委托引用以防止垃圾回收
    private ImageCallbackDelegate _callbackDelegate;
    private HeartBeatLostCallbackDelegate _heartBeatLostCallbackDelegate;
    private HeartBeatLostCallbackDelegate _heartBeatLostReconnectOKDelegate;
    private HeartBeatLostCallbackDelegate _heartBeatLostReconnectFailedDelegate;


    /// <summary>
    /// 包装方法：使用事件机制启动相机（带用户自定义数据）
    /// </summary>
    /// <param name="grab_sleep_time_ms">抓取时间间隔，单位毫秒</param>
    /// <param name="userData">用户自定义数据，在启动相机时传入</param>
    /// <returns>启动状态</returns>
    public CAM_STATUS StartCameraWithEvent(uint grab_sleep_time_ms) 
    {
        // 创建回调委托并保存引用（防止被垃圾回收）
        // 使用 lambda 捕获当前实例，实现实例级别的回调
        _callbackDelegate = (imgPtr, r3Ptr) => 
        {
            // 创建 ImgT 对象（注意：不拥有内存所有权，由 C++ 层管理）
            ImgT img = new ImgT(imgPtr, false);
            
            // 触发当前实例的事件
            this.ImageReceived?.Invoke(img, this);
        };
        
        // 获取函数指针（非泛型委托可以正常获取）
        System.IntPtr callbackPtr = System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_callbackDelegate);
        
        // 调用原始方法，用户数据完整传递
        return startCameraWithCallback_protected(callbackPtr, grab_sleep_time_ms);
    }
    
    /// <summary>
    /// 清理图像回调相关的资源（应在停止相机后调用）
    /// </summary>
    public void CleanupImageCallback() {
        _callbackDelegate = null;
    }
        


    /// <summary>
    /// 包装方法：使用事件机制连接相机（带心跳丢失回调）
    /// </summary>
    /// <returns>连接状态</returns>
    public CAM_STATUS connectCameraWithEvent(
		uint reconnect_TryTimes,
        uint reconnect_SleepIntervalMs,
		uint heartBeatMs) 
    {
        // 创建心跳丢失回调委托并保存引用（防止被垃圾回收）
        // 使用 lambda 捕获当前实例，实现实例级别的回调
        _heartBeatLostCallbackDelegate = (namePtr, ipPtr, macPtr, msgPtr, callbackUserData) => {
            string name = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(namePtr);
            string ip = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(ipPtr);
            string mac = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(macPtr);
            string msg = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(msgPtr);
            
            // 触发当前实例的事件
            this.HeartBeatLost?.Invoke(name, ip, mac, msg, this);
        };
        
        // 获取函数指针（非泛型委托可以正常获取）
        System.IntPtr callbackPtr = System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_heartBeatLostCallbackDelegate);
        

        _heartBeatLostReconnectOKDelegate = (namePtr, ipPtr, macPtr, msgPtr, callbackUserData) => {
            string name = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(namePtr);
            string ip = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(ipPtr);
            string mac = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(macPtr);
            string msg = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(msgPtr);
            
            // 触发当前实例的事件
            this.HeartBeatLost_ReconnectOK?.Invoke(name, ip, mac, msg, this);
        };
        
        System.IntPtr reconnectOKCallback = System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_heartBeatLostReconnectOKDelegate);

        _heartBeatLostReconnectFailedDelegate = (namePtr, ipPtr, macPtr, msgPtr, callbackUserData) => {
            string name = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(namePtr);
            string ip = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(ipPtr);
            string mac = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(macPtr);
            string msg = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(msgPtr);
            
            // 触发当前实例的事件
            this.HeartBeatLost_ReconnectFailed?.Invoke(name, ip, mac, msg, this);
        };
        
        System.IntPtr reconnectFailedCallback = System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_heartBeatLostReconnectFailedDelegate);


        // 调用原始方法，用户数据完整传递
        return connectCameraWithCallback_protected(
            reconnect_TryTimes, reconnect_SleepIntervalMs, heartBeatMs, 
            callbackPtr, reconnectOKCallback, reconnectFailedCallback
        );

    }


    // 包装方法：使用事件机制连接相机（带心跳丢失回调）
    // <returns>连接状态</returns>
    // public CAM_STATUS ConnectCameraWithEvent() {
    //     return ConnectCameraWithEvent(1000, 1, System.IntPtr.Zero);
    // }
    
    // 包装方法：使用事件机制连接相机（带心跳丢失回调和自定义参数）
    // <param name="microSecond">超时时间，单位微微秒</param>
    // <param name="numCallbackThreadsInPool">回调线程池中的线程数</param>
    // <param name="userData">用户自定义数据，在连接相机时传入</param>
    // <returns>连接状态</returns>
    // public CAM_STATUS ConnectCameraWithEvent(uint microSecond, uint numCallbackThreadsInPool, System.IntPtr userData) {
    //     // 创建心跳丢失回调委托并保存引用（防止被垃圾回收）
    //     // 使用 lambda 捕获当前实例，实现实例级别的回调
    //     _heartBeatLostCallbackDelegate = (namePtr, ipPtr, macPtr, msgPtr, callbackUserData) => {
    //         string name = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(namePtr);
    //         string ip = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(ipPtr);
    //         string mac = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(macPtr);
    //         string msg = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(msgPtr);
            
    //         // 触发当前实例的事件
    //         this.HeartBeatLost?.Invoke(name, ip, mac, msg, callbackUserData);
    //     };
        
    //     // 获取函数指针（非泛型委托可以正常获取）
    //     System.IntPtr callbackPtr = System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_heartBeatLostCallbackDelegate);
        
    //     // 调用原始方法，用户数据完整传递
    //     return connectCameraWithCallback_protected(callbackPtr, microSecond, numCallbackThreadsInPool, userData);
    // }

  /// <summary>获取初始化结果。</summary>
  /// <returns>
  ///     - CAM_STATUS::ERROR_NULL_PTR_DEV	初始化失败。  Initialize failed.
  ///     - CAM_STATUS::All_OK				</returns>
  public CAM_STATUS isReady() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_isReady(swigCPtr);
    return ret;
  }

  /// <summary>【不推荐。请使用带回调版本的函数】连接相机</summary>
  /// 连接相机的动作包括：打开设备句柄，打开数据流句柄，加载参数文件，扫描相机参数。
  /// 当相机连接时，采集图像过程并没有开始。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED	相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_SCAN_PARAMETERS	扫描相机参数时发生错误。 Error happened when scanning parameters in device.</returns>
  public CAM_STATUS connectCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_connectCamera(swigCPtr);
    return ret;
  }

  /// <summary>【不推荐。请使用带回调版本的函数】开始采集</summary>
  /// 开始采集的动作包括：加载标定文件，申请相机缓存，锁定相机参数，开始采集图像。
  ///
  ///
  /// It will load calibration file, initialize device buffer, lock device parameters, start acquisition.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_START_ACQUISITION		相机开始采集失败。  Failed to start acquisition.
  ///     - CAM_STATUS::ERROR_CALIBRATION_PATH		使用标定文件初始化标定变量错误。 Error happened when initializing calibration variables.</returns>
  public CAM_STATUS startCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_startCamera(swigCPtr);
    return ret;
  }

  /// <summary>【推荐】启动取图像线程池，用于 callback 图像回调函数。此函数建议在 connect 之后调用一次即可。不建议在 start 之前和 stop 之后调用。相机start之后，禁止调用</summary>
  /// 线程的创建和销毁会消耗 CPU 资源，建议开启线程池。
  /// 不建议在 start 之前和 stop 之后调用。相机start之后，禁止调用
  ///
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		 Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	 Camera is disconnected.</returns>
  public CAM_STATUS enableCallbackThreadsInPool(uint threadsNumber, bool enable) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_enableCallbackThreadsInPool__SWIG_0(swigCPtr, threadsNumber, enable);
    return ret;
  }

  /// <summary>【推荐】启动取图像线程池，用于 callback 图像回调函数。此函数建议在 connect 之后调用一次即可。不建议在 start 之前和 stop 之后调用。相机start之后，禁止调用</summary>
  /// 线程的创建和销毁会消耗 CPU 资源，建议开启线程池。
  /// 不建议在 start 之前和 stop 之后调用。相机start之后，禁止调用
  ///
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		 Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	 Camera is disconnected.</returns>
  public CAM_STATUS enableCallbackThreadsInPool(uint threadsNumber) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_enableCallbackThreadsInPool__SWIG_1(swigCPtr, threadsNumber);
    return ret;
  }

  /// <summary>【弃用，建议参考新的心跳函数： connectCamera(6 参数版本) 】尝试重新连接相机</summary>
  /// 当失去相机心跳时，相机的指针将暂时不可用。当重新发现相机后，可以调用此程序，恢复相机的指针。
  /// <returns>
  ///     - CAM_STATUS::All_OK					重新连接成功。
  ///     - CAM_STATUS::CAM_IS_XXXXXXXXXXXX	    重新连接成功后，再调用此函数，将返回相机的状态。见 getStatus()。
  ///     - CAM_STATUS::CAM_IS_DISCONNECTED 	重新连接成功后，再调用此函数，将返回相机的状态。一般，相机将处于 Disconnected 状态。
  ///     - CAM_STATUS::ERROR_CAM_IS_LOST		丢失心跳后，相机将处于此状态。</returns>
  public CAM_STATUS reconnectCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_reconnectCamera(swigCPtr);
    return ret;
  }

  /// <summary>停止采集</summary>
  /// 停止采集的动作包括：停止采集图像，解锁相机参数，清除相机缓存。本质上 connected 和 stopped 是一样的状态。
  ///
  ///
  /// It will stop acquisition, unlock device parameter, free device buffer. Actually, connected equals to stopped.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_STOP_ACQUISITION		相机停止采集失败。  Failed to stop acquisition.</returns>
  public CAM_STATUS stopCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_stopCamera(swigCPtr);
    return ret;
  }

  /// <summary>断开相机连接</summary>
  /// 断开相机连接的动作包括：关闭数据流句柄，关闭设备句柄。
  ///
  ///
  /// It will close datastream, close device handle.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED	相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::UNKNOWN					未知错误。  Unknown problem.</returns>
  public CAM_STATUS disconnectCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_disconnectCamera(swigCPtr);
    return ret;
  }

  /// <summary>【若使用 callback 图像回调，则无需调用】获取图像</summary>
  /// 相机必须处于 start 状态时才可以采集图像。请注意，【非线程安全】。
  /// <returns>
  ///     - CAM_STATUS::All_OK                  成功获得图像。
  ///     - CAM_STATUS::TIME_OUT                超时，请重试。
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED	相机处于 start 状态。  Camera is started.</returns>
  public CAM_STATUS getImageData(ImgT imgTable) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_getImageData(swigCPtr, ImgT.getCPtr(imgTable));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置 Y 方向分辨率。仅对标定后数据有效。</summary>
  /// 点云 y 坐标 = Y_offset + Y_scale * Y_pixelValueInRange。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setScaleY(double value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setScaleY(swigCPtr, value);
    return ret;
  }

  /// <summary>启用相机内部标定（包含 Calibration + Rectification），标定由相机完成。这个是（推荐）做法。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由 rectificationWidth 确定，也就是参数 [Scan3dRectificationWidth_Scan3dExtractionSelector_Scan3dExtraction1]。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice(uint rectificationWidth, bool range_Uint16, bool enableOpenMP) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice__SWIG_0(swigCPtr, rectificationWidth, range_Uint16, enableOpenMP);
    return ret;
  }

  /// <summary>启用相机内部标定（包含 Calibration + Rectification），标定由相机完成。这个是（推荐）做法。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由 rectificationWidth 确定，也就是参数 [Scan3dRectificationWidth_Scan3dExtractionSelector_Scan3dExtraction1]。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice(uint rectificationWidth, bool range_Uint16) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice__SWIG_1(swigCPtr, rectificationWidth, range_Uint16);
    return ret;
  }

  /// <summary>启用相机内部标定（包含 Calibration + Rectification），标定由相机完成。这个是（推荐）做法。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由 rectificationWidth 确定，也就是参数 [Scan3dRectificationWidth_Scan3dExtractionSelector_Scan3dExtraction1]。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice(uint rectificationWidth) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice__SWIG_2(swigCPtr, rectificationWidth);
    return ret;
  }

  /// <summary>启用相机内部标定（包含 Calibration + Rectification），标定由相机完成。这个是（推荐）做法。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由 rectificationWidth 确定，也就是参数 [Scan3dRectificationWidth_Scan3dExtractionSelector_Scan3dExtraction1]。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice__SWIG_3(swigCPtr);
    return ret;
  }

  /// <summary>启用相机内部标定（只做 Calibration，不做 Rectification），标定由相机完成。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由参数 [Width_RegionSelector_Region1] 控制。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice_CalibrateAC(bool range_Uint16, bool rangeX_Uint16, bool enableOpenMP) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice_CalibrateAC__SWIG_0(swigCPtr, range_Uint16, rangeX_Uint16, enableOpenMP);
    return ret;
  }

  /// <summary>启用相机内部标定（只做 Calibration，不做 Rectification），标定由相机完成。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由参数 [Width_RegionSelector_Region1] 控制。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice_CalibrateAC(bool range_Uint16, bool rangeX_Uint16) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice_CalibrateAC__SWIG_1(swigCPtr, range_Uint16, rangeX_Uint16);
    return ret;
  }

  /// <summary>启用相机内部标定（只做 Calibration，不做 Rectification），标定由相机完成。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由参数 [Width_RegionSelector_Region1] 控制。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice_CalibrateAC(bool range_Uint16) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice_CalibrateAC__SWIG_2(swigCPtr, range_Uint16);
    return ret;
  }

  /// <summary>启用相机内部标定（只做 Calibration，不做 Rectification），标定由相机完成。需要提前发送标定文件到相机中（一体式相机已在出厂时放置）。</summary>
  ///
  /// 相机内标定，最终图像的宽度，由参数 [Width_RegionSelector_Region1] 控制。
  ///
  /// 如果 [rangeTypeUint16] 设置为 true，请特别注意：标定后的 Range 数据要使用 DataNames::RAN_CAL_16 表示，是 uin16_t 类型。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_OPERATION_NOT_ALLOW	无法启用相机内部标定。原因可能是相机不支持此功能。详见说明文档中列举的支持相机型号。</returns>
  public CAM_STATUS setCalibration_inDevice_CalibrateAC() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inDevice_CalibrateAC__SWIG_3(swigCPtr);
    return ret;
  }

  /// <summary>禁用标定，从相机端只获得原始数据</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setCalibration_No() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_No(swigCPtr);
    return ret;
  }

  /// <summary>加载相机的参数文件，csv 格式import Configuretion File.</summary>
  /// 相机必须处于 connected 或者 stopped 状态。csv 参数文件必须和相机的固件版本相兼容。
  /// 否则会导入失败。
  ///
  ///
  /// The camera must be connected or stopped when calling this.
  /// The parameters version in CSV file must match the device. If not, it might be failed.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。		Camera is disconnected.
  ///     - CAM_STATUS::ERROR_CSV_PATH				无效的文件路径。				Invalid file path.</returns>
  public CAM_STATUS importConfiguretionFile(string filePath) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_importConfiguretionFile(swigCPtr, filePath);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>导出相机的参数文件，csv 格式</summary>
  /// 相机必须处于 connected 或者 stopped 状态。
  /// The camera must be connected or stopped when calling this function.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.
  ///     - CAM_STATUS::ERROR_CSV_PATH				无效的文件路径。				Invalid file path.</returns>
  public CAM_STATUS exportConfiguretionFile(string filePath) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_exportConfiguretionFile(swigCPtr, filePath);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置相机取图的最大等待时间（会直接影响 stop 的执行速度，所以建议设小一点），默认值见 DEFAULT_TIMEOUTSet timeout.The default is DEFAULT_TIMEOUT</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setTimeOut(uint value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setTimeOut(swigCPtr, value);
    return ret;
  }

  /// <summary>设置图像缓存的张数</summary>
  /// 默认是 20 ，最小可以设置为 1。设置越大，内存占用越多。设置太小，有丢帧风险。
  ///
  ///
  /// The default is 20, available minimum value can be 1. The bigger value, the more memory will be allocated. The smaller value, the higher risk of miss a frame.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		 Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	 Camera is disconnected.</returns>
  public CAM_STATUS setBufferCount(uint value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setBufferCount(swigCPtr, value);
    return ret;
  }

  /// <summary>启用边缘增强功能。</summary>
  /// This is for raw image only. The supported using mode is:
  /// [Grab raw image only, then calibrate image by EzR or in-PC funtions.]
  /// <returns>
  ///     - CAM_STATUS::All_OK</returns>
  public CAM_STATUS enableCorrectRawImageEdgeEffect(bool enable) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_enableCorrectRawImageEdgeEffect__SWIG_0(swigCPtr, enable);
    return ret;
  }

  /// <summary>启用边缘增强功能。</summary>
  /// This is for raw image only. The supported using mode is:
  /// [Grab raw image only, then calibrate image by EzR or in-PC funtions.]
  /// <returns>
  ///     - CAM_STATUS::All_OK</returns>
  public CAM_STATUS enableCorrectRawImageEdgeEffect() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_enableCorrectRawImageEdgeEffect__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>设置 IP 地址Set IP address.</summary>
  /// Title: 详细说明 Introduction
  /// 设置相机的 IP/Subnet 的过程较为复杂。请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 设置分为“永久性 IP/Subnet 设置” 与 “临时性 IP/Subnet 设置”。
  ///
  /// When setting IP, please follow the description here strictly;
  /// The settings include "Persistent IP/Subnet setting" and "Temporary IP/Subnet setting".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet 设置  Persistent IP/Subnet setting.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行持久设置。
  /// 关闭电源时，IP 将被保留。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to perform persistent setting.
  /// The IP will be kept when power off.
  ///
  ///
  ///
  /// 执行“永久性 IP/Subnet设置”时，设置成功后，setIP() 将返回 CAM_STATUS::ALL_OK。
  /// &lt;但是&gt; 您必须调用 R3S::scanDevice() 以重新扫描所有设备！然后再次连接相机。
  ///
  /// When executing "Persistent IP/Subnet setting", if setting successfully,
  /// setIP() will return CAM_STATUS::ALL_OK. &lt;BUT&gt; You must call R3S::scanDevice()
  /// to scan all device again! And after that, re-connect the device.
  /// Title: 临时性 IP/Subnet 设置  Force IP, temporary IP/Subnet setting.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForcoIP"，
  /// 这将设置临时 IP/Subnet。关闭电源后，新设置的 IP/Subnet 将丢失，
  /// 设备将恢复成设置前的 IP/Subnet 地址。
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will perform temporary IP/Subnet setting
  /// which has been called "ForceIP". The new IP will be lost when power off.
  ///
  ///
  ///
  ///
  ///
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.
  ///     - CAM_STATUS::ERROR_SET_IP				相机设置失败。				Setting failed.</returns> 
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is avaliable.
  public CAM_STATUS setIp(string IP, bool isPersistent) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setIp__SWIG_0(swigCPtr, IP, isPersistent);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置 IP 地址Set IP address.</summary>
  /// Title: 详细说明 Introduction
  /// 设置相机的 IP/Subnet 的过程较为复杂。请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 设置分为“永久性 IP/Subnet 设置” 与 “临时性 IP/Subnet 设置”。
  ///
  /// When setting IP, please follow the description here strictly;
  /// The settings include "Persistent IP/Subnet setting" and "Temporary IP/Subnet setting".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet 设置  Persistent IP/Subnet setting.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行持久设置。
  /// 关闭电源时，IP 将被保留。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to perform persistent setting.
  /// The IP will be kept when power off.
  ///
  ///
  ///
  /// 执行“永久性 IP/Subnet设置”时，设置成功后，setIP() 将返回 CAM_STATUS::ALL_OK。
  /// &lt;但是&gt; 您必须调用 R3S::scanDevice() 以重新扫描所有设备！然后再次连接相机。
  ///
  /// When executing "Persistent IP/Subnet setting", if setting successfully,
  /// setIP() will return CAM_STATUS::ALL_OK. &lt;BUT&gt; You must call R3S::scanDevice()
  /// to scan all device again! And after that, re-connect the device.
  /// Title: 临时性 IP/Subnet 设置  Force IP, temporary IP/Subnet setting.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForcoIP"，
  /// 这将设置临时 IP/Subnet。关闭电源后，新设置的 IP/Subnet 将丢失，
  /// 设备将恢复成设置前的 IP/Subnet 地址。
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will perform temporary IP/Subnet setting
  /// which has been called "ForceIP". The new IP will be lost when power off.
  ///
  ///
  ///
  ///
  ///
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.
  ///     - CAM_STATUS::ERROR_SET_IP				相机设置失败。				Setting failed.</returns> 
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is avaliable.
  public CAM_STATUS setIp(string IP) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setIp__SWIG_1(swigCPtr, IP);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置 Subnet 地址Set Subnet address.</summary>
  /// Title: 详细说明 Introduction
  /// 设置相机的 IP/Subnet 的过程较为复杂。请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 设置分为“永久性 IP/Subnet 设置” 与 “临时性 IP/Subnet 设置”。
  ///
  /// When setting IP, please follow the description here strictly;
  /// The settings include "Persistent IP/Subnet setting" and "Temporary IP/Subnet setting".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet 设置  Persistent IP/Subnet setting.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行持久设置。
  /// 关闭电源时，IP 将被保留。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to perform persistent setting.
  /// The IP will be kept when power off.
  ///
  ///
  ///
  /// 执行“永久性 IP/Subnet设置”时，设置成功后，setIP() 将返回 CAM_STATUS::ALL_OK。
  /// &lt;但是&gt; 您必须调用 R3S::scanDevice() 以重新扫描所有设备！然后再次连接相机。
  ///
  /// When executing "Persistent IP/Subnet setting", if setting successfully,
  /// setIP() will return CAM_STATUS::ALL_OK. &lt;BUT&gt; You must call R3S::scanDevice()
  /// to scan all device again! And after that, re-connect the device.
  /// Title: 临时性 IP/Subnet 设置  Force IP, temporary IP/Subnet setting.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForcoIP"，
  /// 这将设置临时 IP/Subnet。关闭电源后，新设置的 IP/Subnet 将丢失，
  /// 设备将恢复成设置前的 IP/Subnet 地址。
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will perform temporary IP/Subnet setting
  /// which has been called "ForceIP". The new IP will be lost when power off.
  ///
  ///
  ///
  ///
  ///
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.
  ///     - CAM_STATUS::ERROR_SET_SUBNET			相机设置失败。				Setting failed.</returns> 
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is avaliable.
  public CAM_STATUS setSubnet(string Su, bool isPersistent) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setSubnet__SWIG_0(swigCPtr, Su, isPersistent);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置 Subnet 地址Set Subnet address.</summary>
  /// Title: 详细说明 Introduction
  /// 设置相机的 IP/Subnet 的过程较为复杂。请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 设置分为“永久性 IP/Subnet 设置” 与 “临时性 IP/Subnet 设置”。
  ///
  /// When setting IP, please follow the description here strictly;
  /// The settings include "Persistent IP/Subnet setting" and "Temporary IP/Subnet setting".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet 设置  Persistent IP/Subnet setting.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行持久设置。
  /// 关闭电源时，IP 将被保留。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to perform persistent setting.
  /// The IP will be kept when power off.
  ///
  ///
  ///
  /// 执行“永久性 IP/Subnet设置”时，设置成功后，setIP() 将返回 CAM_STATUS::ALL_OK。
  /// &lt;但是&gt; 您必须调用 R3S::scanDevice() 以重新扫描所有设备！然后再次连接相机。
  ///
  /// When executing "Persistent IP/Subnet setting", if setting successfully,
  /// setIP() will return CAM_STATUS::ALL_OK. &lt;BUT&gt; You must call R3S::scanDevice()
  /// to scan all device again! And after that, re-connect the device.
  /// Title: 临时性 IP/Subnet 设置  Force IP, temporary IP/Subnet setting.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForcoIP"，
  /// 这将设置临时 IP/Subnet。关闭电源后，新设置的 IP/Subnet 将丢失，
  /// 设备将恢复成设置前的 IP/Subnet 地址。
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will perform temporary IP/Subnet setting
  /// which has been called "ForceIP". The new IP will be lost when power off.
  ///
  ///
  ///
  ///
  ///
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.
  ///     - CAM_STATUS::ERROR_SET_SUBNET			相机设置失败。				Setting failed.</returns> 
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is avaliable.
  public CAM_STATUS setSubnet(string Su) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setSubnet__SWIG_1(swigCPtr, Su);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置设备参数，即 csv 文件中的参数。【不支持 started 时设置参数】Set the device parameters, which are shown in csv file.</summary>
  /// 设置参数时，相机必须处于 connected 或者 stopped。
  ///
  ///
  /// 如果需要设置其他参数，请见 3.3.0.4 之后的新增接口：setParameter()
  ///
  /// The camera must be connected or stopped when setting parameters.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED			相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED		相机处于 disconnect 状态。	Camera is disconnected.
  ///     - CAM_STATUS::ERROR_PARAMETER_VALUE_INVALID	设置值非法。					Invalid setting value.
  ///     - CAM_STATUS::ERROR_PARAMETER_INVALID			设置失败。					Setting failed.</returns>
  public CAM_STATUS setParameterValue(string ParamterName, string value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setParameterValue(swigCPtr, ParamterName, value);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【推荐。完全兼容 setParameterValue ，不支持 started 时设置参数】设置设备参数（不仅包含 csv 文件中的参数，还可以是其他有多级 selector 的参数）。但是，需要注意“可写”的参数一般都在 csv 文件中，所以这里主要考虑的是一些“指令”参数，比如 xxxReset 之类。Set the device parameters.</summary>
  /// 设置参数时，相机必须处于 connected 或者 stopped【不支持 started 时设置参数】。
  ///
  ///
  /// 注意，Ranger3Studio 中的参数，根据功能，可以分为 3 种：这个函数支持 1 和 2。
  ///
  /// - 1 数值型：整数、小数、字符串；Ranger3Studio 上体现为【输入框 / Editbox】。
  ///
  /// - 2 使能型：布尔（使用 0，1 表示）；Ranger3Studio 上体现为【勾选框 / CheckBox】。
  ///
  /// - 3 命令型：Ranger3Studio 上体现为【按钮 / Button】。如需使用此类型参数，请调用 excuteCommand()
  ///
  /// The camera must be connected or stopped when setting parameters.
  /// 相机参数名的推导。
  ///
  ///
  /// 例子一：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 ImageFormatControl
  ///
  /// 2. 选择 RegionSelector 的下拉框，再选择 ComponentSelector 的下拉框，然后找到 ComponentEnable 勾选框（0/1）。
  ///
  /// RegionSelector_Scan3dExtraction1
  ///
  ///                                |____ComponentSelector_Reflectance
  ///
  ///                                                                  |____ComponentEnable
  ///
  /// 3. 仿造下面的结果，可以推导出适当的参数名。
  ///
  /// 上例中，推导的参数名为：ComponentEnable_ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1
  ///
  /// 并且，勾选框的参数可选值为 0/1。
  /// 例子二：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 DeviceControl
  ///
  /// 2. 选择 DeviceScanType 下拉框。
  ///
  /// 3. 上例中，推导的参数名为：DeviceScanType。这里没有多级的 selector 。
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED			相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED		相机处于 disconnect 状态。	Camera is disconnected.
  ///     - CAM_STATUS::ERROR_PARAMETER_VALUE_INVALID	设置值非法。					Invalid setting value.
  ///     - CAM_STATUS::ERROR_PARAMETER_INVALID			设置失败。					Setting failed.</returns>
  public CAM_STATUS setParameter(string ParamterName, string value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setParameter(swigCPtr, ParamterName, value);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>读取 Y 方向分辨率Get scale in Y axis.</summary>
  /// 点云 y 坐标 = Y_offset + Y_scale * Y_pixelValueInRange。
  ///
  ///
  /// Y value of a pointcloud = Y_offset + Y_scale * Y_pixelValueInRange.
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera should be connected or stopped.
  public double getScaleY() {
    double ret = SwigRanger3PINVOKE.Ranger3_getScaleY(swigCPtr);
    return ret;
  }

  /// <summary>【不建议继续使用，功能冗余。读取空数据的像素值，可以通过解析图像数据来获得。】Get missing data.</summary>
  /// MissingData 表示用于填补空数据的像素值，默认 -1.0e6，见宏 MISSING_DATA。
  ///
  ///
  /// The value is to fill in the empty pixels, the default is -1.0e6, see MISSING_DATA.
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera should be connected or stopped.
  public float getMissingData() {
    float ret = SwigRanger3PINVOKE.Ranger3_getMissingData(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用】读取使用 PC 标定时，设定的参数文件路径Get parameters file path.</summary>
  /// <returns>
  ///     - "" 空字符串表示未导入参数文件。  Empty string. Mo parameters file.</returns> 
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera should be connected or stopped.
  public string getParametPath() {
    string ret = SwigRanger3PINVOKE.Ranger3_getParametPath(swigCPtr);
    return ret;
  }

  /// <summary>读取相机取图的最大等待时间，单位毫秒，默认值见 DEFAULT_TIMEOUTGet maximum waiting time when grabbing image, unit is millimeter. The defalut is DEFAULT_TIMEOUT.</summary>
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera shoudl be connected or stopped.
  public uint getTimeOut() {
    uint ret = (uint)SwigRanger3PINVOKE.Ranger3_getTimeOut(swigCPtr);
    
    return ret;
}

  /// <summary>读取图像缓存的张数Get the number of image buffers.</summary>
  /// 默认是 20 ，最小可以设置为 1。设置越大，内存占用越多。设置太小，有丢帧风险。
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// The default is 20, avaliable minimum value can be 1. The bigger value, the more memory will be allocated. The smaller value, the higher risk of miss a frame.
  /// Camera shoudl be connected or stopped.
  public uint getBufferCount() {
    uint ret = (uint)SwigRanger3PINVOKE.Ranger3_getBufferCount(swigCPtr);
    
    return ret;
}

  /// <summary>从设备上重新读取 IP 地址，该算子会和相机进行通讯。Get IP address from device.</summary>
  /// <returns>
  ///     -  "" 错误返回空字符串。  return empty string when error happened.</returns> 
  /// Title: 详细说明 Introduction
  /// 读取相机的 IP/Subnet 时，请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 分为“永久性 IP/Subnet ” 与 “临时性 IP/Subnet ”。
  ///
  /// When getting IP, please follow the description here strictly;
  /// The IP/Subnet include "Persistent IP/Subnet" and "Temporary IP/Subnet".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet   Persisitent IP/Subnet.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行读取“永久性 IP”。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to get persistent IP.
  ///
  ///
  ///
  /// Title: 临时性 IP/Subnet  Force IP, temporary IP/Subnet.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForceIP"
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will get temporary IP/Subnet
  ///
  ///
  ///
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is available.
  public string getIp(bool isPersistent) {
    string ret = SwigRanger3PINVOKE.Ranger3_getIp__SWIG_0(swigCPtr, isPersistent);
    return ret;
  }

  /// <summary>从设备上重新读取 IP 地址，该算子会和相机进行通讯。Get IP address from device.</summary>
  /// <returns>
  ///     -  "" 错误返回空字符串。  return empty string when error happened.</returns> 
  /// Title: 详细说明 Introduction
  /// 读取相机的 IP/Subnet 时，请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 分为“永久性 IP/Subnet ” 与 “临时性 IP/Subnet ”。
  ///
  /// When getting IP, please follow the description here strictly;
  /// The IP/Subnet include "Persistent IP/Subnet" and "Temporary IP/Subnet".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet   Persisitent IP/Subnet.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行读取“永久性 IP”。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to get persistent IP.
  ///
  ///
  ///
  /// Title: 临时性 IP/Subnet  Force IP, temporary IP/Subnet.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForceIP"
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will get temporary IP/Subnet
  ///
  ///
  ///
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is available.
  public string getIp() {
    string ret = SwigRanger3PINVOKE.Ranger3_getIp__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>读取 IP 地址，IP 地址是实现保存在成员变量中的，不会和相机通讯。Get IP address.</summary>
  /// <returns>
  ///     -  "" 错误返回空字符串。  return empty string when error happened.</returns> 
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is available.
  public string get_DeviceIP() {
    string ret = SwigRanger3PINVOKE.Ranger3_get_DeviceIP(swigCPtr);
    return ret;
  }

  /// <summary>读心跳计数。当心跳停止的时候，这个值不会在变化。Get Heart beats count.</summary>
  /// <returns>
  ///     -  "" 错误返回空字符串。  return empty string when error happened.</returns> 
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is available.
  public ulong get_Heartbeat_Count() {
    ulong ret = SwigRanger3PINVOKE.Ranger3_get_Heartbeat_Count(swigCPtr);
    return ret;
  }

  /// <summary>读取 SubnetGet Subnet.</summary>
  /// <returns>
  ///     - "" 错误返回空字符串。  return empty string when error happened.</returns> 
  /// Title: 详细说明 Introduction
  /// 读取相机的 IP/Subnet 时，请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 分为“永久性 IP/Subnet ” 与 “临时性 IP/Subnet ”。
  ///
  /// When getting IP, please follow the description here strictly;
  /// The IP/Subnet include "Persistent IP/Subnet" and "Temporary IP/Subnet".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet   Persistent IP/Subnet.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行读取“永久性 IP”。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to get persistent IP.
  ///
  ///
  ///
  /// Title: 临时性 IP/Subnet  Force IP, temporary IP/Subnet.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForcoIP"
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will get temporary IP/Subnet
  ///
  ///
  ///
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is avaliable.
  public string getSubNet(bool isPersistent) {
    string ret = SwigRanger3PINVOKE.Ranger3_getSubNet__SWIG_0(swigCPtr, isPersistent);
    return ret;
  }

  /// <summary>读取 SubnetGet Subnet.</summary>
  /// <returns>
  ///     - "" 错误返回空字符串。  return empty string when error happened.</returns> 
  /// Title: 详细说明 Introduction
  /// 读取相机的 IP/Subnet 时，请严格按照这里给出的说明操作。
  /// 相机的 IP/Subnet 分为“永久性 IP/Subnet ” 与 “临时性 IP/Subnet ”。
  ///
  /// When getting IP, please follow the description here strictly;
  /// The IP/Subnet include "Persistent IP/Subnet" and "Temporary IP/Subnet".
  ///
  ///
  ///
  /// Title: 永久性 IP/Subnet   Persistent IP/Subnet.
  /// 相机必须处于 connected 或者 stopped 状态。请将"isPersistent"设置为 true 以执行读取“永久性 IP”。
  ///
  /// Camera must be connected or stopped. Please set "isPersistent" as true to get persistent IP.
  ///
  ///
  ///
  /// Title: 临时性 IP/Subnet  Force IP, temporary IP/Subnet.
  /// 相机必须处于 disconnected 状态。请将"isPersistent"设置为 false。它将执行"ForcoIP"
  ///
  /// Camera must be disconnected. Please set "isPersistent" as false;
  /// It will get temporary IP/Subnet
  ///
  ///
  ///
  /// 相机处于 started 状态时，不可执行以上任何一种设置。
  ///
  ///
  /// When camera is started, neither settings is avaliable.
  public string getSubNet() {
    string ret = SwigRanger3PINVOKE.Ranger3_getSubNet__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>MAC 地址支持任何相机状态下读取。MAC 地址不可修改，出厂固定。支持 disconnect 读取，网络断开读取。MAC. can be queried in any camera status. MAC. is unchangeable.</summary>
  /// <returns>
  ///     - "" 错误返回空字符串。  return "" when error happened.</returns>
  public string getMac() {
    string ret = SwigRanger3PINVOKE.Ranger3_getMac(swigCPtr);
    return ret;
  }

  /// <summary>设备名格式： "SICKGigEVisionTL_DEV_" + mac + "_Ranger3"Device name format : "SICKGigEVisionTL_DEV_" + mac + "_Ranger3"</summary>
  /// <returns>
  ///     - 以字符串形式输出结果。
  ///     - "" 错误返回空字符串。  return "" when error happened.</returns> 
  /// 支持任何相机状态下读取。
  ///
  ///
  /// It can be queried in any camera status..
  public string getDeviceName() {
    string ret = SwigRanger3PINVOKE.Ranger3_getDeviceName(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 getParameter("DeviceTemperature") 】读取相机温度，可以通过 getParameter 读取参数 【DeviceTemperature】Read device temperature.</summary>
  /// <returns>
  ///     - 以字符串形式输出结果。
  ///     - "" 错误返回空字符串。  return "" when error happened.</returns> 
  /// 支持任何相机状态下读取。
  ///
  ///
  /// It can be queried in any camera status..
  public string getTemperature() {
    string ret = SwigRanger3PINVOKE.Ranger3_getTemperature(swigCPtr);
    return ret;
  }

  /// <summary>读取 csv 文件中的相机参数，相机不可处于 started。【如需要在 started 时读取参数，可使用 getParameter 】Get the device parameters shown in csv file.</summary>
  /// <returns>
  ///     - "" 错误，返回空字符串。  return empty string when error happened.</returns> 
  /// 相机必须处于 connected 或者 stopped 状态。
  ///
  ///
  /// The camera must be connected or stopped when calling this.
  public string getParameterValue(string ParameterName) {
    string ret = SwigRanger3PINVOKE.Ranger3_getParameterValue(swigCPtr, ParameterName);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>读取 csv 文件中的相机参数、Ranger3Studio 中的只读参数、指令等。支持包含多级 selector 的参数。【相机可以处于 started。如果遇到不支持读取的参数会抛出异常】 。Get the device parameters.</summary>
  /// <returns>
  ///     - "" 错误，返回空字符串。  return empty string when error happened.</returns> 
  /// 相机必须处于 connected 状态。
  ///
  ///
  /// 特别地，这个函数支持在 started 状态下读取某些参数。某一参数是否支持在 started 状态读写，请根据实际情况测试为准。
  ///
  /// 注意，Ranger3Studio 中的参数，根据功能，可以分为 3 种：这个函数支持 1 和 2。
  ///
  /// - 1 数值型：整数、小数、字符串；Ranger3Studio 上体现为【输入框 / Editbox】。
  ///
  /// - 2 使能型：布尔（使用 0，1 表示）；Ranger3Studio 上体现为【勾选框 / CheckBox】。
  ///
  /// - 3 命令型：Ranger3Studio 上体现为【按钮 / Button】。如需使用此类型参数，请调用 excuteCommand()
  ///
  /// The camera must be connected when calling this.
  /// 相机参数名的推导。
  ///
  ///
  /// 例子一：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 ImageFormatControl
  ///
  /// 2. 选择 RegionSelector 的下拉框，再选择 ComponentSelector 的下拉框，然后找到 ComponentEnable 勾选框（0/1）。
  ///
  /// RegionSelector_Scan3dExtraction1
  ///
  ///                                |____ComponentSelector_Reflectance
  ///
  ///                                                                  |____ComponentEnable
  ///
  /// 3. 仿造下面的结果，可以推导出适当的参数名。
  ///
  /// 上例中，推导的参数名为：ComponentEnable_ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1
  ///
  /// 并且，勾选框的参数可选值为 0/1。
  ///
  ///
  ///
  /// 例子二：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 DeviceControl
  ///
  /// 2. 选择 DeviceScanType 下拉框。
  ///
  /// 3. 上例中，推导的参数名为：DeviceScanType。这里没有多级的 selector 。
  public string getParameter(string ParameterName) {
    string ret = SwigRanger3PINVOKE.Ranger3_getParameter(swigCPtr, ParameterName);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Get string of all parameters.</summary>
  public string getParametersAsStructureString() {
    string ret = SwigRanger3PINVOKE.Ranger3_getParametersAsStructureString(swigCPtr);
    return ret;
  }

  /// <summary>Get string of device info.</summary>
  /// 请在 connected 或者 stopped 状态下读取。
  ///
  ///
  /// 其中设备基本参数，也可以使用下面的函数读取，
  ///
  /// this-&gt;getParameterValue()
  ///
  ///
  ///
  /// 参见例程：Demo_R3_05_read_device_information.cpp
  public string getDeviceInfoAsStructureString() {
    string ret = SwigRanger3PINVOKE.Ranger3_getDeviceInfoAsStructureString(swigCPtr);
    return ret;
  }

  /// <summary>读取相机状态。Get camera status.</summary>
  /// <returns>
  ///     - CAM_STATUS::CAM_IS_CONNECTED		相机已连接 Connected
  ///     - CAM_STATUS::CAM_IS_STARTED			相机开始采集 Start acquisition
  ///     - CAM_STATUS::CAM_IS_STOPPED			相机停止采集 Stop acquisition
  ///     - CAM_STATUS::CAM_IS_DISCONNECTED		相机未连接 Disconnected
  ///     - CAM_STATUS::ERROR_CAM_IS_LOST		PC无法和相机建立连接 Cannot communicate with camera.
  ///     - CAM_STATUS::ERROR_NULL_PTR_DEV		类 Ranger3 的对象未初始化完成 Class Ranger3 initialization undone.</returns>
  public CAM_STATUS getStatus() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_getStatus(swigCPtr);
    return ret;
  }

  /// <summary>读取相机的心跳状态。Get camera status.</summary>
  /// <returns>
  ///     - true		相机心跳读取正常
  ///     - false       相机心跳读取异常</returns>
  public bool getHeartBeat() {
    bool ret = SwigRanger3PINVOKE.Ranger3_getHeartBeat(swigCPtr);
    return ret;
  }

  /// <summary>读取相机类型。Get camera type.</summary>
  /// <returns>
  ///     - _RANGER3</returns>
  public CamType getCamType() {
    CamType ret = (CamType)SwigRanger3PINVOKE.Ranger3_getCamType(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用。可通过解析图像数据获得，这样更加合理】读取图像序号，也是当前取到的图像总数，stop 后清理。Get image ID. The value is also the number of grabbed image. Reset to 0 when stopped.</summary>
  /// 0初始。相机必须处于 connected 或者 stopped 状态。
  ///
  ///
  /// Start from 0. The camera must be connected or stopped when calling this.
  public ulong getImgID() {
    ulong ret = SwigRanger3PINVOKE.Ranger3_getImgID(swigCPtr);
    return ret;
  }

  /// <summary>更新相机固件。此函数将会阻塞，请运行后重新扫描相机。</summary>
  ///
  /// 过程 1: Link/Data 闪烁，表示发送固件文件到相机。
  ///
  /// 过程 2: State 闪烁，表示正在执行固件升级，请不要断开相机电源。
  public bool updateFirmware(string firmwarePackagePath) {
    bool ret = SwigRanger3PINVOKE.Ranger3_updateFirmware(swigCPtr, firmwarePackagePath);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【CS 专用，用于获得相机的完整参数列表】更新相机参数信息。这是会和相机通讯，遍历相机内部参数。</summary>
  /// <returns>是否成功更新参数信息。</returns>
  public bool updateParamtersInfo() {
    bool ret = SwigRanger3PINVOKE.Ranger3_updateParamtersInfo(swigCPtr);
    return ret;
  }

  /// <summary>【CS 专用，用于获得相机的完整参数列表】获取所有参数组的名称列表</summary>
  /// <returns>所有参数组的名称列表。</returns>
  public StringVector paramCategoryList() {
    StringVector ret = new StringVector(SwigRanger3PINVOKE.Ranger3_paramCategoryList(swigCPtr), true);
    return ret;
  }

  /// <summary>【CS 专用，用于获得相机的完整参数列表】获取指定参数组的参数全名列表</summary>
  /// <param name="categoryName">	参数组的名称。</param> 
  /// <returns>参数组的全名列表。</returns>
  public StringVector paramFullNameOfCategory(string categoryName) {
    StringVector ret = new StringVector(SwigRanger3PINVOKE.Ranger3_paramFullNameOfCategory(swigCPtr, categoryName), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【CS 专用，用于获得相机的完整参数列表】获取所有参数的全名列表</summary>
  /// <returns>所有参数的全名列表。</returns>
  public StringVector paramFullNameList() {
    StringVector ret = new StringVector(SwigRanger3PINVOKE.Ranger3_paramFullNameList(swigCPtr), true);
    return ret;
  }

  /// <summary>【CS 专用，用于获得相机的完整参数列表】获取当前参数的值</summary>
  /// <param name="paramFullName">	参数的全名。</param> 
  /// <returns>当前参数的值。</returns>
  public string paramCurrentValue(string paramFullName) {
    string ret = SwigRanger3PINVOKE.Ranger3_paramCurrentValue(swigCPtr, paramFullName);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【CS 专用，用于获得相机的完整参数列表】获取当前参数的可选值列表</summary>
  /// <param name="paramFullName">	参数的全名。</param> 
  /// <param name="currentValueId">	当前参数的值的索引。</param> 
  /// <returns>可选值列表。</returns>
  public StringVector paramOptionalValues(string paramFullName, out int currentValueId) {
    StringVector ret = new StringVector(SwigRanger3PINVOKE.Ranger3_paramOptionalValues(swigCPtr, paramFullName, out currentValueId), true);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取图模式为 2D</summary>
  public bool E2U_2DMode() {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_2DMode(swigCPtr);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取图模式为 3D</summary>
  public bool E2U_3DMode(bool needReflectance) {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_3DMode__SWIG_0(swigCPtr, needReflectance);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取图模式为 3D</summary>
  public bool E2U_3DMode() {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_3DMode__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取剖面触发为内部时钟</summary>
  public bool E2U_GrabBy_FreeRunning(int imgH, int lineRate) {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_GrabBy_FreeRunning__SWIG_0(swigCPtr, imgH, lineRate);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取剖面触发为内部时钟</summary>
  public bool E2U_GrabBy_FreeRunning(int imgH) {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_GrabBy_FreeRunning__SWIG_1(swigCPtr, imgH);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取剖面触发为内部时钟</summary>
  public bool E2U_GrabBy_FreeRunning() {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_GrabBy_FreeRunning__SWIG_2(swigCPtr);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取剖面触发为外部编码器</summary>
  public bool E2U_GrabBy_Encoder(int imgH, bool frameTrigger) {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_GrabBy_Encoder__SWIG_0(swigCPtr, imgH, frameTrigger);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取剖面触发为外部编码器</summary>
  public bool E2U_GrabBy_Encoder(int imgH) {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_GrabBy_Encoder__SWIG_1(swigCPtr, imgH);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置取剖面触发为外部编码器</summary>
  public bool E2U_GrabBy_Encoder() {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_GrabBy_Encoder__SWIG_2(swigCPtr);
    return ret;
  }

  /// <summary>【建议必看，作为例子学习】易用接口（Easy To Use）：设置激光频闪</summary>
  public bool E2U_LaserFlash() {
    bool ret = SwigRanger3PINVOKE.Ranger3_E2U_LaserFlash(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】读取标定的矫正方法Get rectification methods.</summary>
  /// 详见标定过程的介绍。
  ///
  ///
  /// More details please see the user documents.
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera should be connected or stopped.
  public RectMethod getRectMethos(bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    RectMethod ret = (RectMethod)SwigRanger3PINVOKE.Ranger3_getRectMethos__SWIG_0(swigCPtr, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】读取标定的矫正方法Get rectification methods.</summary>
  /// 详见标定过程的介绍。
  ///
  ///
  /// More details please see the user documents.
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera should be connected or stopped.
  public RectMethod getRectMethos() {
    RectMethod ret = (RectMethod)SwigRanger3PINVOKE.Ranger3_getRectMethos__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>启用 PC 标定，从相机端只获得原始数据，标定过程在PC端完成，需要设置标定文件。标定文件支持 json 和 xml。推荐使用 jsonEnable in-PC calibration, calibration file required.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_CALIBRATION_PATH		标定参数文件的路径不正确。  Calibration file path is invalid.</returns>
  public CAM_STATUS setCalibration_inPC(string filePath, bool toDoRectify, uint rectificationWidth, int threadsNumber_X64Only, int runMode) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inPC__SWIG_0(swigCPtr, filePath, toDoRectify, rectificationWidth, threadsNumber_X64Only, runMode);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>启用 PC 标定，从相机端只获得原始数据，标定过程在PC端完成，需要设置标定文件。标定文件支持 json 和 xml。推荐使用 jsonEnable in-PC calibration, calibration file required.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_CALIBRATION_PATH		标定参数文件的路径不正确。  Calibration file path is invalid.</returns>
  public CAM_STATUS setCalibration_inPC(string filePath, bool toDoRectify, uint rectificationWidth, int threadsNumber_X64Only) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inPC__SWIG_1(swigCPtr, filePath, toDoRectify, rectificationWidth, threadsNumber_X64Only);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>启用 PC 标定，从相机端只获得原始数据，标定过程在PC端完成，需要设置标定文件。标定文件支持 json 和 xml。推荐使用 jsonEnable in-PC calibration, calibration file required.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_CALIBRATION_PATH		标定参数文件的路径不正确。  Calibration file path is invalid.</returns>
  public CAM_STATUS setCalibration_inPC(string filePath, bool toDoRectify, uint rectificationWidth) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inPC__SWIG_2(swigCPtr, filePath, toDoRectify, rectificationWidth);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>启用 PC 标定，从相机端只获得原始数据，标定过程在PC端完成，需要设置标定文件。标定文件支持 json 和 xml。推荐使用 jsonEnable in-PC calibration, calibration file required.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_CALIBRATION_PATH		标定参数文件的路径不正确。  Calibration file path is invalid.</returns>
  public CAM_STATUS setCalibration_inPC(string filePath, bool toDoRectify) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inPC__SWIG_3(swigCPtr, filePath, toDoRectify);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>启用 PC 标定，从相机端只获得原始数据，标定过程在PC端完成，需要设置标定文件。标定文件支持 json 和 xml。推荐使用 jsonEnable in-PC calibration, calibration file required.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - CAM_STATUS::ERROR_CALIBRATION_PATH		标定参数文件的路径不正确。  Calibration file path is invalid.</returns>
  public CAM_STATUS setCalibration_inPC(string filePath) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibration_inPC__SWIG_4(swigCPtr, filePath);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置标定的矫正方法（PC 标定）。如果要设置 in-device 标定的校正方法，请设置参数 【Scan3dRectificationMethod_Scan3dExtractionSelector_Scan3dExtraction1】Set rectification methods.</summary>
  /// 详见标定过程的介绍。
  ///
  ///
  /// More details please see the user documents.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setRectMethos_inPC(RectMethod value, bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setRectMethos_inPC__SWIG_0(swigCPtr, (int)value, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>设置标定的矫正方法（PC 标定）。如果要设置 in-device 标定的校正方法，请设置参数 【Scan3dRectificationMethod_Scan3dExtractionSelector_Scan3dExtraction1】Set rectification methods.</summary>
  /// 详见标定过程的介绍。
  ///
  ///
  /// More details please see the user documents.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setRectMethos_inPC(RectMethod value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setRectMethos_inPC__SWIG_1(swigCPtr, (int)value);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setRectMethos_inPC</summary>
  public CAM_STATUS setRectMethos(RectMethod value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setRectMethos(swigCPtr, (int)value);
    return ret;
  }

  /// <summary>【不建议再继续使用，该参数是使用 xml 标定文件用的，目前已经不起作用】设置启用 SSE ，来加速标定过程的处理速度。Set to enable SSE or not.</summary>
  /// 临时保留，建议设置为 true。
  ///
  ///
  /// temporary parameter, set to true.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.</returns>
  public CAM_STATUS setEnableSSE(bool value, bool do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setEnableSSE__SWIG_0(swigCPtr, value, do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，该参数是使用 xml 标定文件用的，目前已经不起作用】设置启用 SSE ，来加速标定过程的处理速度。Set to enable SSE or not.</summary>
  /// 临时保留，建议设置为 true。
  ///
  ///
  /// temporary parameter, set to true.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.</returns>
  public CAM_STATUS setEnableSSE(bool value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setEnableSSE__SWIG_1(swigCPtr, value);
    return ret;
  }

  /// <summary>【不建议再继续使用，该参数是使用 xml 标定文件用的，目前已经不起作用】设置启用 SSE ，来加速标定过程的处理速度。Set to enable SSE or not.</summary>
  /// 临时保留，建议设置为 true。
  ///
  ///
  /// temporary parameter, set to true.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.</returns>
  public CAM_STATUS setEnableSSE() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setEnableSSE__SWIG_2(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置标定的矫正系数（PC 标定）。如果要设置 in-device 标定的校正系数，请设置参数 【Scan3dRectificationSpread_Scan3dExtractionSelector_Scan3dExtraction1】Set rectification spread.</summary>
  /// 详见标定过程的介绍。这个值越大，图像上的 missing data 越少。
  ///
  ///
  /// More details please see the user documents.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setRectSpread_inPC(double value, bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setRectSpread_inPC__SWIG_0(swigCPtr, value, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置标定的矫正系数（PC 标定）。如果要设置 in-device 标定的校正系数，请设置参数 【Scan3dRectificationSpread_Scan3dExtractionSelector_Scan3dExtraction1】Set rectification spread.</summary>
  /// 详见标定过程的介绍。这个值越大，图像上的 missing data 越少。
  ///
  ///
  /// More details please see the user documents.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setRectSpread_inPC(double value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setRectSpread_inPC__SWIG_1(swigCPtr, value);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setRectSpread_inPC</summary>
  public CAM_STATUS setRectSpread(double value, bool please_do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setRectSpread__SWIG_0(swigCPtr, value, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setRectSpread_inPC</summary>
  public CAM_STATUS setRectSpread(double value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setRectSpread__SWIG_1(swigCPtr, value);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置标定后数据中的无效数据的值（PC 标定）。Set missing data.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。 Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。 Camera is disconnected.</returns>
  public CAM_STATUS setMissingData_inPC(float value, bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setMissingData_inPC__SWIG_0(swigCPtr, value, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置标定后数据中的无效数据的值（PC 标定）。Set missing data.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。 Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。 Camera is disconnected.</returns>
  public CAM_STATUS setMissingData_inPC(float value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setMissingData_inPC__SWIG_1(swigCPtr, value);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setMissingData_inPC</summary>
  public CAM_STATUS setMissingData(float value, bool please_do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setMissingData__SWIG_0(swigCPtr, value, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setMissingData_inPC</summary>
  public CAM_STATUS setMissingData(float value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setMissingData__SWIG_1(swigCPtr, value);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置是否进行矫正，如需矫正，则请指定校正后的图像宽度（PC 标定）。in-device 标定暂不支持Set to rectify or not.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.</returns>
  public CAM_STATUS setDoRectify_inPC(bool toDoRectify, uint rectificationWidth, bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify_inPC__SWIG_0(swigCPtr, toDoRectify, rectificationWidth, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置是否进行矫正，如需矫正，则请指定校正后的图像宽度（PC 标定）。in-device 标定暂不支持Set to rectify or not.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.</returns>
  public CAM_STATUS setDoRectify_inPC(bool toDoRectify, uint rectificationWidth) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify_inPC__SWIG_1(swigCPtr, toDoRectify, rectificationWidth);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置是否进行矫正，如需矫正，则请指定校正后的图像宽度（PC 标定）。in-device 标定暂不支持Set to rectify or not.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.</returns>
  public CAM_STATUS setDoRectify_inPC(bool toDoRectify) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify_inPC__SWIG_2(swigCPtr, toDoRectify);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】设置是否进行矫正，如需矫正，则请指定校正后的图像宽度（PC 标定）。in-device 标定暂不支持Set to rectify or not.</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。			Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	Camera is disconnected.</returns>
  public CAM_STATUS setDoRectify_inPC() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify_inPC__SWIG_3(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setDoRectify_inPC</summary>
  public CAM_STATUS setDoRectify(bool toDoRectify, uint rectificationWidth, bool do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify__SWIG_0(swigCPtr, toDoRectify, rectificationWidth, do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setDoRectify_inPC</summary>
  public CAM_STATUS setDoRectify(bool toDoRectify, uint rectificationWidth) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify__SWIG_1(swigCPtr, toDoRectify, rectificationWidth);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setDoRectify_inPC</summary>
  public CAM_STATUS setDoRectify(bool toDoRectify) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify__SWIG_2(swigCPtr, toDoRectify);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setDoRectify_inPC</summary>
  public CAM_STATUS setDoRectify() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setDoRectify__SWIG_3(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】读取标定的矫正系数（PC 标定）。如果要读取 in-device 标定的校正系数，请读取参数 【Scan3dRectificationSpread_Scan3dExtractionSelector_Scan3dExtraction1】Get rectification spread.</summary>
  /// 详见标定过程的介绍。
  ///
  ///
  /// More details please see the user documents.
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera should be connected or stopped.
  public double getRectSpread_inPC(bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    double ret = SwigRanger3PINVOKE.Ranger3_getRectSpread_inPC__SWIG_0(swigCPtr, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。】读取标定的矫正系数（PC 标定）。如果要读取 in-device 标定的校正系数，请读取参数 【Scan3dRectificationSpread_Scan3dExtractionSelector_Scan3dExtraction1】Get rectification spread.</summary>
  /// 详见标定过程的介绍。
  ///
  ///
  /// More details please see the user documents.
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera should be connected or stopped.
  public double getRectSpread_inPC() {
    double ret = SwigRanger3PINVOKE.Ranger3_getRectSpread_inPC__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 getRectSpread_inPC</summary>
  public double getRectSpread(bool please_do_not_use_it_any_more) {
    double ret = SwigRanger3PINVOKE.Ranger3_getRectSpread__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 getRectSpread_inPC</summary>
  public double getRectSpread() {
    double ret = SwigRanger3PINVOKE.Ranger3_getRectSpread__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。标定文件在相机中，无需给额外定标定文件路径】读取标定文件的路径Get calibration file path.</summary>
  /// <returns>
  ///     - "" 空字符串表示未导入标定文件，输出未标定的原始数据据。  Empty string. No calibration file, output uncalibrated image.</returns> 
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera shoudl be connected or stopped.
  public string getCalibrationPath_inPC(bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    string ret = SwigRanger3PINVOKE.Ranger3_getCalibrationPath_inPC__SWIG_0(swigCPtr, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定。标定文件在相机中，无需给额外定标定文件路径】读取标定文件的路径Get calibration file path.</summary>
  /// <returns>
  ///     - "" 空字符串表示未导入标定文件，输出未标定的原始数据据。  Empty string. No calibration file, output uncalibrated image.</returns> 
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera shoudl be connected or stopped.
  public string getCalibrationPath_inPC() {
    string ret = SwigRanger3PINVOKE.Ranger3_getCalibrationPath_inPC__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 getCalibrationPath_inPC</summary>
  public string getCalibraPath(bool please_do_not_use_it_any_more) {
    string ret = SwigRanger3PINVOKE.Ranger3_getCalibraPath__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 getCalibrationPath_inPC</summary>
  public string getCalibraPath() {
    string ret = SwigRanger3PINVOKE.Ranger3_getCalibraPath__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setParameter("EncoderReset", "") 】重置编码器计数，等价于 excuteCommand("EncoderReset")。 	</summary>
  public bool resetEncoder(bool do_not_use_it_any_more) {
    bool ret = SwigRanger3PINVOKE.Ranger3_resetEncoder__SWIG_0(swigCPtr, do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setParameter("EncoderReset", "") 】重置编码器计数，等价于 excuteCommand("EncoderReset")。 	</summary>
  public bool resetEncoder() {
    bool ret = SwigRanger3PINVOKE.Ranger3_resetEncoder__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定，setCalibration_inDevice_CalibrateAC()】读取是否进行矫正（PC 标定）。 in-device 暂不支持。Get to rectify or not.</summary>
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera shoudl be connected or stopped.
  public bool getDoRectify_inPC(bool do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice) {
    bool ret = SwigRanger3PINVOKE.Ranger3_getDoRectify_inPC__SWIG_0(swigCPtr, do_not_use_it____inPC_Calibration_will_be_replaced_by_inDevice);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用In-Device标定，setCalibration_inDevice_CalibrateAC()】读取是否进行矫正（PC 标定）。 in-device 暂不支持。Get to rectify or not.</summary>
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera shoudl be connected or stopped.
  public bool getDoRectify_inPC() {
    bool ret = SwigRanger3PINVOKE.Ranger3_getDoRectify_inPC__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 getDoRectify_inPC</summary>
  public bool getDoRectify(bool please_do_not_use_it_any_more) {
    bool ret = SwigRanger3PINVOKE.Ranger3_getDoRectify__SWIG_0(swigCPtr, please_do_not_use_it_any_more);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 getDoRectify_inPC</summary>
  public bool getDoRectify() {
    bool ret = SwigRanger3PINVOKE.Ranger3_getDoRectify__SWIG_1(swigCPtr);
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setCalibration_No(), setCalibration_inDevice(), setCalibration_inPC() 】设置标定文件的路径 / Set calibration file path.</summary>
  public CAM_STATUS setCalibraPath(string do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setCalibraPath(swigCPtr, do_not_use_it_any_more);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setParameter("Some-Command", "") 】执行相机的某些指令。Excute device command.</summary>
  /// <returns>
  ///     - true  设置成功。
  ///     - false 设置失败。</returns> 
  /// 相机必须处于 connected，或者 stopped 状态。
  ///
  ///
  /// 注意，Ranger3Studio 中的参数，根据功能，可以分为 3 种：这个函数支持 3。
  ///
  /// - 1 数值型：整数、小数、字符串；Ranger3Studio 上体现为【输入框 / Editbox】。
  ///
  /// - 2 使能型：布尔（使用 0，1 表示）；Ranger3Studio 上体现为【勾选框 / CheckBox】。
  ///
  /// - 3 命令型：Ranger3Studio 上体现为【按钮 / Button】。如需使用此类型参数，请调用 excuteCommand()
  ///
  /// The camera must be connected or stopped when calling this.
  ///
  ///
  /// *
  /// 相机参数名的推导。
  ///
  ///
  /// 例子一：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 ImageFormatControl
  ///
  /// 2. 选择 RegionSelector 的下拉框，再选择 ComponentSelector 的下拉框，然后找到 ComponentEnable 勾选框（0/1）。
  ///
  /// RegionSelector_Scan3dExtraction1
  ///
  ///                                |____ComponentSelector_Reflectance
  ///
  ///                                                                  |____ComponentEnable
  ///
  /// 3. 仿造下面的结果，可以推导出适当的参数名。
  ///
  /// 上例中，推导的参数名为：ComponentEnable_ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1
  ///
  /// 并且，勾选框的参数可选值为 0/1。
  ///
  ///
  ///
  /// 例子二：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 DeviceControl
  ///
  /// 2. 选择 DeviceScanType 下拉框。
  ///
  /// 3. 上例中，推导的参数名为：DeviceScanType。这里没有多级的 selector 。
  public bool excuteCommand(string CommandName, bool do_not_use_it_any_more) {
    bool ret = SwigRanger3PINVOKE.Ranger3_excuteCommand__SWIG_0(swigCPtr, CommandName, do_not_use_it_any_more);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 setParameter("Some-Command", "") 】执行相机的某些指令。Excute device command.</summary>
  /// <returns>
  ///     - true  设置成功。
  ///     - false 设置失败。</returns> 
  /// 相机必须处于 connected，或者 stopped 状态。
  ///
  ///
  /// 注意，Ranger3Studio 中的参数，根据功能，可以分为 3 种：这个函数支持 3。
  ///
  /// - 1 数值型：整数、小数、字符串；Ranger3Studio 上体现为【输入框 / Editbox】。
  ///
  /// - 2 使能型：布尔（使用 0，1 表示）；Ranger3Studio 上体现为【勾选框 / CheckBox】。
  ///
  /// - 3 命令型：Ranger3Studio 上体现为【按钮 / Button】。如需使用此类型参数，请调用 excuteCommand()
  ///
  /// The camera must be connected or stopped when calling this.
  ///
  ///
  /// *
  /// 相机参数名的推导。
  ///
  ///
  /// 例子一：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 ImageFormatControl
  ///
  /// 2. 选择 RegionSelector 的下拉框，再选择 ComponentSelector 的下拉框，然后找到 ComponentEnable 勾选框（0/1）。
  ///
  /// RegionSelector_Scan3dExtraction1
  ///
  ///                                |____ComponentSelector_Reflectance
  ///
  ///                                                                  |____ComponentEnable
  ///
  /// 3. 仿造下面的结果，可以推导出适当的参数名。
  ///
  /// 上例中，推导的参数名为：ComponentEnable_ComponentSelector_Reflectance_RegionSelector_Scan3dExtraction1
  ///
  /// 并且，勾选框的参数可选值为 0/1。
  ///
  ///
  ///
  /// 例子二：
  ///
  /// 在 Ranger3Studio 中的多级参数结构中，如果有如下的结构。
  ///
  /// 1. 选择页面 DeviceControl
  ///
  /// 2. 选择 DeviceScanType 下拉框。
  ///
  /// 3. 上例中，推导的参数名为：DeviceScanType。这里没有多级的 selector 。
  public bool excuteCommand(string CommandName) {
    bool ret = SwigRanger3PINVOKE.Ranger3_excuteCommand__SWIG_1(swigCPtr, CommandName);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 importConfiguretionFile() 】设置参数文件路径 / Set parameters file path.</summary>
  public CAM_STATUS setParametPath(string do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_setParametPath(swigCPtr, do_not_use_it_any_more);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 exportConfiguretionFile() 】保存参数文件为 csv 格式。/ Save parameters to file.</summary>
  public CAM_STATUS saveParameterToCSV(string do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_saveParameterToCSV(swigCPtr, do_not_use_it_any_more);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>【不建议再继续使用，请使用代替函数 importConfiguretionFile() 】加载 csv 参数文件。/ Load parameters from file.</summary>
  public CAM_STATUS loadParameterFrCSV(string do_not_use_it_any_more) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_loadParameterFrCSV(swigCPtr, do_not_use_it_any_more);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Ranger3 createFromIpMac(string ip_mac, bool useIP, CameraShared cameraShared) {
    global::System.IntPtr cPtr = SwigRanger3PINVOKE.Ranger3_createFromIpMac(ip_mac, useIP, CameraShared.getCPtr(cameraShared));
    Ranger3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ranger3(cPtr, false);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CAM_STATUS connectCameraWithCallback_protected(uint reconnect_TryTimes, uint reconnect_SleepIntervalMs, uint heartBeatMs, System.IntPtr pCallback_Lost, System.IntPtr pCallback_ReConnectOK, System.IntPtr pCallback_ReConnectFailed) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_connectCameraWithCallback_protected(swigCPtr, reconnect_TryTimes, reconnect_SleepIntervalMs, heartBeatMs, pCallback_Lost, pCallback_ReConnectOK, pCallback_ReConnectFailed);
    return ret;
  }

  public CAM_STATUS startCameraWithCallback_protected(System.IntPtr callback, uint grab_sleep_time_ms) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_startCameraWithCallback_protected(swigCPtr, callback, grab_sleep_time_ms);
    return ret;
  }

  public CAM_STATUS sendFileToCamera(string filePath) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_sendFileToCamera(swigCPtr, filePath);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string retrieveFileFromCamera() {
    string ret = SwigRanger3PINVOKE.Ranger3_retrieveFileFromCamera(swigCPtr);
    return ret;
  }

  public CAM_STATUS deleteFileFromCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_deleteFileFromCamera(swigCPtr);
    return ret;
  }

  public CAM_STATUS userSet_load(int id) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_userSet_load(swigCPtr, id);
    return ret;
  }

  public CAM_STATUS userSet_save(int id) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_userSet_save(swigCPtr, id);
    return ret;
  }

  public CAM_STATUS userSet_set_default(int id) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_userSet_set_default(swigCPtr, id);
    return ret;
  }

  public CAM_STATUS userSet_set_description(int id, string description) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Ranger3_userSet_set_description(swigCPtr, id, description);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string userSet_get_description(int id) {
    string ret = SwigRanger3PINVOKE.Ranger3_userSet_get_description(swigCPtr, id);
    return ret;
  }

}

}
