//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>激光线图像数据信息  Sensor image data information.</summary>

public class SensoInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SensoInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SensoInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SensoInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SensoInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_SensoInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SensoInfo() : this(SwigRanger3PINVOKE.new_SensoInfo(), true) {
  }

  ///  sensor 图像宽度。Width of sensor image
  public uint cols {
    set {
      SwigRanger3PINVOKE.SensoInfo_cols_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.SensoInfo_cols_get(swigCPtr);
      return ret;
    } 
  }

  ///  sensor 图像高度。Height of sensor image.
  public uint rows {
    set {
      SwigRanger3PINVOKE.SensoInfo_rows_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.SensoInfo_rows_get(swigCPtr);
      return ret;
    } 
  }

  ///  sensor 图像起始列，始终为0，表示使用全部区域。The default is zero.
  public uint senOffsetX {
    set {
      SwigRanger3PINVOKE.SensoInfo_senOffsetX_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.SensoInfo_senOffsetX_get(swigCPtr);
      return ret;
    } 
  }

  ///  sensor 图像起始行，始终为0，表示使用全部区域。The default is zero.	
  public uint senOffsetY {
    set {
      SwigRanger3PINVOKE.SensoInfo_senOffsetY_set(swigCPtr, value);
    } 
    get {
      uint ret = SwigRanger3PINVOKE.SensoInfo_senOffsetY_get(swigCPtr);
      return ret;
    } 
  }

}

}
