//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {

public class SwigRanger3 {
  public static uint STATUS_BIT_ENABLE {
    get {
      uint ret = SwigRanger3PINVOKE.STATUS_BIT_ENABLE_get();
      return ret;
    } 
  }

  public static uint STATUS_BIT_ENCODER_A {
    get {
      uint ret = SwigRanger3PINVOKE.STATUS_BIT_ENCODER_A_get();
      return ret;
    } 
  }

  public static uint STATUS_BIT_ENCODER_B {
    get {
      uint ret = SwigRanger3PINVOKE.STATUS_BIT_ENCODER_B_get();
      return ret;
    } 
  }

  public static uint STATUS_BIT_OVERTRIG {
    get {
      uint ret = SwigRanger3PINVOKE.STATUS_BIT_OVERTRIG_get();
      return ret;
    } 
  }

  public static uint STATUS_BIT_LINE_TRIGGER {
    get {
      uint ret = SwigRanger3PINVOKE.STATUS_BIT_LINE_TRIGGER_get();
      return ret;
    } 
  }

  public static uint STATUS_BIT_ENCODER_RESET {
    get {
      uint ret = SwigRanger3PINVOKE.STATUS_BIT_ENCODER_RESET_get();
      return ret;
    } 
  }

  public static void mark_Obsolete(SWIGTYPE_p_SPtrT_CustomerLog_t plog, string deviceName, string fname_old, string fname_new) {
    SwigRanger3PINVOKE.mark_Obsolete(SWIGTYPE_p_SPtrT_CustomerLog_t.getCPtr(plog), deviceName, fname_old, fname_new);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
  }

  public static bool isEnvironmentVariableExisted(string name) {
    bool ret = SwigRanger3PINVOKE.isEnvironmentVariableExisted(name);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  ///
  ///
  /// <summary>typdef and #define set for STL \ GenICam \ SICK GenIRanger</summary>
  ///
  /// <remarks>	This is the Ranger3 GenIcam API wrapper.</remarks>
  ///
  /// 	&lt;remarks&gt;Copyright 2016-2026 SICK AG. All rights reserved.	&lt;/remarks&gt;
  /// Author: Vision Lab, SICK GCN
  public static readonly float MISSING_DATA = SwigRanger3PINVOKE.MISSING_DATA_get();
  public static readonly int PFNC_Mono8 = SwigRanger3PINVOKE.PFNC_Mono8_get();
  public static readonly int PFNC_Mono12p = SwigRanger3PINVOKE.PFNC_Mono12p_get();
  public static readonly int PFNC_Mono16 = SwigRanger3PINVOKE.PFNC_Mono16_get();
  public static readonly int PFNC_Coord3D_C12p = SwigRanger3PINVOKE.PFNC_Coord3D_C12p_get();
  public static readonly int PFNC_Coord3D_C16 = SwigRanger3PINVOKE.PFNC_Coord3D_C16_get();
  public static readonly int PFNC_Mono4p = SwigRanger3PINVOKE.PFNC_Mono4p_get();
  public static readonly int CHUNK_DATA_SIZE = SwigRanger3PINVOKE.CHUNK_DATA_SIZE_get();
  public static readonly int CHUNK_DATA_WIDTH = SwigRanger3PINVOKE.CHUNK_DATA_WIDTH_get();
  public static readonly int RANGE_A_ID = SwigRanger3PINVOKE.RANGE_A_ID_get();
  public static readonly int HIRES_IMG_WIDTH = SwigRanger3PINVOKE.HIRES_IMG_WIDTH_get();
  public static readonly int HANDLE_NUM = SwigRanger3PINVOKE.HANDLE_NUM_get();
  public static readonly int R3_VERSION_1 = SwigRanger3PINVOKE.R3_VERSION_1_get();
  public static readonly int R3_VERSION_2 = SwigRanger3PINVOKE.R3_VERSION_2_get();
  public static readonly int R3_VERSION_3 = SwigRanger3PINVOKE.R3_VERSION_3_get();
  public static readonly int R3_VERSION_4 = SwigRanger3PINVOKE.R3_VERSION_4_get();
  public static readonly string R3_VERSION_TIME = SwigRanger3PINVOKE.R3_VERSION_TIME_get();
}

}
