//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>每个 Trispector 对应应该初始化为一个 类Trispector 的对象。Each Trispector device corresponding to a Trispector class object.</summary>

public class Trispector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Trispector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Trispector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Trispector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Trispector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_Trispector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>获取初始化结果。To get initialization result.</summary>
  /// <returns>
  ///     - ERROR_NULL_PTR_DEV	初始化失败。  Initialize failed.
  ///     - CAM_STATUS::All_OK				</returns>
  public CAM_STATUS isReady() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_isReady(swigCPtr);
    return ret;
  }

  /// <summary>连接相机Connect a camera.</summary>
  /// 连接相机的动作包括：打开设备句柄，打开数据流句柄，加载参数文件，扫描相机参数。
  /// 当相机连接时，采集图像过程并没有开始。
  ///
  ///
  /// It will open device handle, open datastream, loading parameters file, scan parameters in device.
  /// When camera is connected, image acquition is not started.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED	相机处于 start 状态。  Camera is started.
  ///     - ERROR_SCAN_PARAMETERS	扫描相机参数时发生错误。 Error happened when scaning parameters in device.</returns>
  public CAM_STATUS connectCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_connectCamera(swigCPtr);
    return ret;
  }

  /// <summary>开始采集Start acquisition.</summary>
  /// 开始采集的动作包括：加载标定文件，申请相机缓存，锁定相机参数，开始采集图像。
  ///
  ///
  /// It will load calibration file, initialize device buffer, lock device parameter, start acquisition.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - ERROR_START_ACQUISITION		相机开始采集失败。  Failed to start acquisition.
  ///     - ERROR_CALIBRATION_PATH				使用标定文件初始化标定变量错误。 Error happened when initialzing calibration variables.</returns>
  public CAM_STATUS startCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_startCamera__SWIG_0(swigCPtr);
    return ret;
  }

  /// <summary>开始采集，并启动 callback 。Start acquisition and passing callback function</summary>
  /// 开始采集的动作包括：加载标定文件，申请相机缓存，锁定相机参数，开始采集图像。
  ///
  /// Callback 函数中的第一个参数是返回的图像。其内存由 API 管理，在 callback 函数调用结束后，API 将释放 ImgT 中的内存。
  ///
  /// 所以，使用者在拿到数据之后，应该第一时间做“深拷贝”。
  ///
  /// ImgT 中的操作符 = ，已经重载为深拷贝。
  /// It will load calibration file, initialize device buffer, lock device parameter, start acquisition.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - ERROR_START_ACQUISITION		相机开始采集失败。  Failed to start acquisition.
  ///     - ERROR_CALIBRATION_PATH				使用标定文件初始化标定变量错误。 Error happened when initialzing calibration variables.</returns>
  public CAM_STATUS startCamera(SWIGTYPE_p_f_p_SickCam__ImgT_p_void__void pCallback, System.IntPtr any) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_startCamera__SWIG_1(swigCPtr, SWIGTYPE_p_f_p_SickCam__ImgT_p_void__void.getCPtr(pCallback), any);
    return ret;
  }

  /// <summary>开始采集，并启动 callback 。Start acquisition and passing callback function</summary>
  /// 开始采集的动作包括：加载标定文件，申请相机缓存，锁定相机参数，开始采集图像。
  ///
  /// Callback 函数中的第一个参数是返回的图像。其内存由 API 管理，在 callback 函数调用结束后，API 将释放 ImgT 中的内存。
  ///
  /// 所以，使用者在拿到数据之后，应该第一时间做“深拷贝”。
  ///
  /// ImgT 中的操作符 = ，已经重载为深拷贝。
  /// It will load calibration file, initialize device buffer, lock device parameter, start acquisition.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - ERROR_START_ACQUISITION		相机开始采集失败。  Failed to start acquisition.
  ///     - ERROR_CALIBRATION_PATH				使用标定文件初始化标定变量错误。 Error happened when initialzing calibration variables.</returns>
  public CAM_STATUS startCamera(SWIGTYPE_p_f_p_SickCam__ImgT_p_void__void pCallback) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_startCamera__SWIG_2(swigCPtr, SWIGTYPE_p_f_p_SickCam__ImgT_p_void__void.getCPtr(pCallback));
    return ret;
  }

  /// <summary>停止采集Stop acquisition.</summary>
  /// 停止采集的动作包括：停止采集图像，解锁相机参数，清除相机缓存。本质上 connected 和 stopped 是一样的状态。
  ///
  ///
  /// It will stop acquisition, unlock device parameter, free device buffer. Actually, connected equals to stopped.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.
  ///     - ERROR_STOP_ACQUISITION		相机停止采集失败。  Failed to stop acquisition.</returns>
  public CAM_STATUS stopCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_stopCamera(swigCPtr);
    return ret;
  }

  /// <summary>断开相机连接Disconnect a camera.</summary>
  /// 断开相机连接的动作包括：关闭数据流句柄，关闭设备句柄。
  ///
  ///
  /// It will close datastream, close device handle.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED	相机处于 start 状态。  Camera is started.
  ///     - UNKNOW					未知错误。  Unknown problem.</returns>
  public CAM_STATUS disconnectCamera() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_disconnectCamera(swigCPtr);
    return ret;
  }

  /// <summary>获取图像Get output images.</summary>
  /// 相机必须处于 start 状态时才可以采集图像。请注意，非线程安全。
  ///
  ///
  /// Camera must be started! And it is not thread-safe.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED	相机处于 start 状态。  Camera is started.</returns>
  public CAM_STATUS getImageData(ImgT imgTable) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_getImageData(swigCPtr, ImgT.getCPtr(imgTable));
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>设置 Y 方向分辨率Set scale in Y axis.</summary>
  /// 点云 y 坐标 = Y_offset + Y_scale * Y_pixelValueInRange。
  ///
  ///
  /// Y value of a pointcloud = Y_offset + Y_scale * Y_pixelValueInRange.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setScaleY(double value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_setScaleY(swigCPtr, value);
    return ret;
  }

  /// <summary>设置相机取图的最大等待时间，默认值见 DEFAULT_TIMEOUTSet timeout.The defalut is DEFAULT_TIMEOUT</summary>
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。  Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。  Camera is disconnected.</returns>
  public CAM_STATUS setTimeOut(uint value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_setTimeOut(swigCPtr, value);
    return ret;
  }

  /// <summary>设置图像缓存的张数Set the number of image buffers.</summary>
  /// 默认是 20 ，最小可以设置为 1。设置越大，内存占用越多。设置太小，有丢帧风险。
  ///
  ///
  /// The default is 20, avaliable minimum value can be 1. The bigger value, the more memory will be allocated. The smaller value, the higher risk of miss a frame.
  /// <returns>
  ///     - CAM_STATUS::All_OK
  ///     - CAM_STATUS::ERROR_CAM_IS_STARTED		相机处于 start 状态。		 Camera is started.
  ///     - CAM_STATUS::ERROR_CAM_IS_DISCONNECTED	相机处于 disconnect 状态。	 Camera is disconnected.</returns>
  public CAM_STATUS setBufferCount(uint value) {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_setBufferCount(swigCPtr, value);
    return ret;
  }

  /// <summary>读取 Y 方向分辨率Get scale in Y axis.</summary>
  /// 点云 y 坐标 = Y_offset + Y_scale * Y_pixelValueInRange。
  ///
  ///
  /// Y value of a pointcloud = Y_offset + Y_scale * Y_pixelValueInRange.
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera shoudl be connected or stopped.
  public double getScaleY() {
    double ret = SwigRanger3PINVOKE.Trispector_getScaleY(swigCPtr);
    return ret;
  }

  /// <summary>读取相机取图的最大等待时间，单位毫秒，默认值见 DEFAULT_TIMEOUTGet maximum waiting time when grabbing image, unit is millimeter. The defalut is DEFAULT_TIMEOUT.</summary>
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// Camera shoudl be connected or stopped.
  public uint getTimeOut() {
    uint ret = (uint)SwigRanger3PINVOKE.Trispector_getTimeOut(swigCPtr);
    
    return ret;
}

  /// <summary>读取图像缓存的张数Get the number of image buffers.</summary>
  /// 默认是 20 ，最小可以设置为 1。设置越大，内存占用越多。设置太小，有丢帧风险。
  /// 建议在相机处于 connected 或者 Stopped 状态时，执行该操作。
  ///
  ///
  /// The default is 20, avaliable minimum value can be 1. The bigger value, the more memory will be allocated. The smaller value, the higher risk of miss a frame.
  /// Camera shoudl be connected or stopped.
  public uint getBufferCount() {
    uint ret = (uint)SwigRanger3PINVOKE.Trispector_getBufferCount(swigCPtr);
    
    return ret;
}

  /// <summary>读取相机状态。Get camera status.</summary>
  /// <returns>
  ///     - CAM_IS_CONNECTED 相机已连接 Connected
  ///     - CAM_STATUS::CAM_IS_STARTED 相机开始采集 Start acquisition
  ///     - CAM_IS_STOPPED 相机停止采集 Stop acquisition
  ///     - CAM_STATUS::CAM_IS_DISCONNECTED 相机未连接 Disconnected
  ///     - ERROR_NULL_PTR_DEV 类 Trispector 的对象未初始化完成。 Class Trispector initialization undone.</returns>
  public CAM_STATUS getStatus() {
    CAM_STATUS ret = (CAM_STATUS)SwigRanger3PINVOKE.Trispector_getStatus(swigCPtr);
    return ret;
  }

  /// <summary>读取相机类型。Get camera type.</summary>
  /// <returns>
  ///     - _Trispector
  ///     - _TRISPECTOR</returns>
  public CamType getCamType() {
    CamType ret = (CamType)SwigRanger3PINVOKE.Trispector_getCamType(swigCPtr);
    return ret;
  }

  /// <summary>读取图像序号，也是当前取到的图像总数，stop 后清理。Get image ID. The value is also the number of grabbed image. Reset to 0 when stopped.</summary>
  /// 0初始。相机必须处于 connected 或者 stopped 状态。
  ///
  ///
  /// Start from 0. The camera must be connected or stopped when calling this.
  public ulong getImgID() {
    ulong ret = SwigRanger3PINVOKE.Trispector_getImgID(swigCPtr);
    return ret;
  }

  public bool socketInit(string ip, int port) {
    bool ret = SwigRanger3PINVOKE.Trispector_socketInit(swigCPtr, ip, port);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string socketSendCommand(string command) {
    string ret = SwigRanger3PINVOKE.Trispector_socketSendCommand(swigCPtr, command);
    if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
