//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SwigRanger3 {
/// <summary>显示 API 的版本号和更新。</summary>

public class VER : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VER(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VER obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VER obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VER() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigRanger3PINVOKE.delete_VER(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    /// <summary>
    /// SwigRanger3 包装器版本号
    /// </summary>
    public static string SwigRanger3_Version { get; } = "1.0.8";
    
    /// <summary>
    /// SwigRanger3 包装器版本发布时间
    /// </summary>
    public static string SwigRanger3_BuildTime { get; } = "2026-06-08";

    public static string SwigRanger3_VersionInfo() { 
        return "SICK GenICam SDK CS " + SwigRanger3_Version + " " + SwigRanger3_BuildTime;
    }


  public VER() : this(SwigRanger3PINVOKE.new_VER(), true) {
  }

  public static string version_number {
    set {
      SwigRanger3PINVOKE.VER_version_number_set(value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.VER_version_number_get();
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static string version_time {
    set {
      SwigRanger3PINVOKE.VER_version_time_set(value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.VER_version_time_get();
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static string version_name {
    set {
      SwigRanger3PINVOKE.VER_version_name_set(value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.VER_version_name_get();
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static string version_platform {
    set {
      SwigRanger3PINVOKE.VER_version_platform_set(value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.VER_version_platform_get();
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static string version_language {
    set {
      SwigRanger3PINVOKE.VER_version_language_set(value);
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SwigRanger3PINVOKE.VER_version_language_get();
      if (SwigRanger3PINVOKE.SWIGPendingException.Pending) throw SwigRanger3PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  /// <summary>以字符串形式返回版本信息【Ranger3】。</summary>
  public static string __version__() {
    string ret = (string)SwigRanger3PINVOKE.VER___version__();
    
    return ret;
}

  /// <summary>以字符串形式返回版本信息【Trispector】。</summary>
  public static string __version_Trispector() {
    string ret = (string)SwigRanger3PINVOKE.VER___version_Trispector();
    
    return ret;
}

}

}
